IU-Libraries-Joint-Development/essi

app/authorities/qa/authorities/iucat_libraries.rb
app/renderers/holding_location_attribute_renderer.rb
app/services/holding_location_service.rb
config/essi_config.example.yml
spec/authorities/qa/authorities/iucat_libraries_spec.rb
spec/cassettes/iucat_libraries_up.yml
spec/renderers/holding_location_renderer_spec.rb
spec/services/holding_location_service_spec.rb

Should be good for a first iteration, but known things to revisit include:
- Adding new options for display elements, like url
- Modifying label display in editing select field vs display (specifically, keeping/dropping "Bloomington - " prefix)
- Confirming final form of the API once released

[ESSI-9] For holding location, use IUCAT API as authority

---

app/assets/javascripts/hyrax/save_work/required_fields.es6
app/forms/hyrax/bib_record_form.rb
app/forms/hyrax/image_form.rb
app/forms/hyrax/paged_resource_form.rb
app/forms/hyrax/scientific_form.rb
app/views/records/edit_fields/_creator.html.erb
app/views/records/edit_fields/_source_metadata_identifier.html.erb
app/views/records/edit_fields/_title.html.erb

What this includes:
* removing `keyword` as a required field (from all 4 work types)
* adds `source_metadata_identifier` as required field (for the 2 work types carrying that property)
* changes the javascript logic to check completion of all required fields to require only one of the two "mutex" (mutually exclusive) fieldsets, currently comprised of:
* Set A: `title`, `creator`
* Set B: `source_metadata_identifier`
Some notes on implementation:
The view partials that set a field as belonging to `mutex_a` or `mutex_b` are currently at:
`app/views/records/edit_fields/`
and apply across all work types, but they could be moved to worktype-specific folders.  The javascript required fields check is such that if neither or only one of mutex_a/mutex_b are present, they function as normal …

[ESSI-32] Source_metadata_identifier obviates conditionally required metadata

---

app/controllers/catalog_controller.rb
app/forms/hyrax/bib_record_form.rb
app/forms/hyrax/paged_resource_form.rb
app/models/concerns/essi/extended_metadata.rb
app/models/solr_document.rb
app/presenters/hyrax/bib_record_presenter.rb
app/presenters/hyrax/paged_resource_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb

Adds Series, in the following capacities:
- to `ExtendedMetadata` module
- to results of remote metadata lookup when supplying a `source_metadata_identifier`
- to `PagedResource`, `BibRecord` edit forms
- to single-record view
- to catalog search results view, as links
Threw in a couple of other minor tweaks:
- Changed `identifier` display from internal link to external link (since that's the value we're supplying)
- Changed `holding_location` RDF value to come from class call instead of manual specification

[ESSI-35] Add Series property to ExtendedMetadata, UI elements

---

app/controllers/concerns/essi/remote_metadata_lookup_behavior.rb
app/models/vocab/pul_terms.rb
config/application.rb

Using "raw" attributes -- Arrays of Strings, rather than ActiveTriple::Relation values -- gets Work creation to successfully receive and process remote metadata without erroring out.

[ESSI-92] Fix remote metadata creation error with "raw" attributes

---

.gitignore
config/essi_config.example.yml
config/ldap_groups_lookup.exmple.yml

Also adds actual file to ignore list and adds `authorized_ldap_groups:` to example config file.

Adds example file for ldap groups lookup.

---

.dockerignore

We want developers to be able to deploy the Docker image to a local environment without a lot of fiddling or troubleshooting.  One thing preventing that was the lack of a properly migrated development database once the container was running.  This was because the .dockerignore file had a filespec to ignore copying the development SQLite file on build, but the migration state was being copied in so that the Rails app didn't know to flag that migrations were outstanding.
One benefit of including the developer's database file in the build is that the running Rails app in the container will be identical to running it in as a local Rails app because the database will be the same and presumably be pointed to the same Fedora/Solr.
HOW-TO:
So to build correctly and deploy, the local environment …

Ensures that Docker image will deploy and run in local developer environment

---

app/authorities/qa/authorities/iucat_libraries.rb
spec/authorities/qa/authorities/iucat_libraries_spec.rb

In the Docker staging environment, when you go to add a PagedResource you immediately get a generic error as soon as the edit form starts to render.  This is due the secrets configuration file not having a value for the url of the holding location authority service, resulting in a method being called on a nil result.
The configuration obviously needs to have that value added, but this PR adds a guard clause in the authority class to just return an empty object if the service url doesn't exist.  The resulting holding locations dropdown will be empty but at least the edit form can render.

ESSI-74 Fixes inability to add a PagedResource in the staging instance

---

app/controllers/hyrax/paged_resources_controller.rb
app/models/concerns/logical_order.rb
app/models/with_proxy_for_object.rb
config/initializers/modify_active_fedora_node_cache.rb
spec/support/shared_examples/paged_structured_controller.rb

Note that completion of ESSI-24 is also required for full resolution of `#save_structure` bugs, pertaining to job queuing.
This covers:
* aborting a `#save_structure` request if the resource is locked, returning 423 status.
* sharing a `NodeCache` across nested `OrderedList` members, to avoid id collision

[ESSI-36] Apply some #save_structure bugfixes to ESSI (as was to pumpkin)

---

app/assets/javascripts/hyrax/file_manager.es6
app/forms/concerns/essi/paged_resource_form_behavior.rb
app/models/solr_document.rb
app/views/hyrax/base/_file_manager_resource_form.html.erb
app/views/records/edit_fields/_viewing_direction.html.erb
app/views/records/edit_fields/_viewing_hint.html.erb
config/initializers/add_file_manager_form_fields.rb

Required adding and modifying a couple of stock hyrax assets: one javascript, one view partial.
Since a model's form `terms` are used for _both_ deciding what passes `params` sanitizing _and_ what shows up in the general editing form, this does add `viewing_direction` and `viewing_hint` to the Edit form, as a side effect.  In the longer term, we probably want to either hide/remove it, or change the interface from free text to a select box.
One thing this revealed is that any additions you want to make to File Manager sidebar content will necessarily require modifying the stock Hyrax javascript, if you want to the "Save" button-enabling logic to be aware of your new content -- otherwise, users will have to change something _else_ to get the Save button enabled!

[ESSI-139] In the File Manager, add Viewing Direction and Viewing Hint

---

Gemfile
Gemfile.lock
spec/features/create_paged_resource_spec.rb

Updates selenium-webdriver and capybara on the client side to fix incompatibility with headless chrome on CircleCI.  
At some point recently, commits in the repo started failing, even for previously passing PRs when master was merged back in.  This was ultimately determined to be caused by a sudden incompatibility between the server-side headless chrome and the client-side version of the Selenium driver. This was causing failures in the Paged Resource feature test when Javascript interactions were initiated.  
The underlying root cause was incompatible response formats between the client and server when checking for w3c standards compliance.  Updating the Selenium webdriver fixes this, but this then produces many Selenium deprecation errors which are fixed by updating Capybara.

ESSI-279: Fixing problem suddenly breaking all commits and PRs

---

config/environment.rb
config/environments/development.rb

If this assignment returns nil, things get broken, so this adds a nil guard to resume the normal default value of an empty hash.

Resolve possible null value for default_url_options to empty hash

---

Gemfile.lock
app/models/ability.rb
app/models/concerns/iu_user_roles.rb
app/models/user.rb
spec/factories/users.rb
spec/features/create_paged_resource_spec.rb
spec/models/ability_spec.rb
spec/models/user_spec.rb

Should serve to satisfy ESSI-168, and/or as a basis for further changes.

[ESSI-168] Restrict "Institution" access by LDAP groups

---

app/models/ability.rb
spec/models/ability_spec.rb

Some parts of the stack assume admins are in the registered group, but
that now depends on the user being in a valid ldap group.

Admins are always in the registered user group.

---

.circleci/config.yml
app/models/ability.rb
app/models/user.rb

For ESSI-344, adds the corresponding change to the Ability model into the User model.

Admins are always in registered user group, in user#groups method

---

app/views/hyrax/base/_items.html.erb
app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/base/_work_title.erb
app/views/hyrax/base/show.html.erb
config/locales/hyrax.en.yml
spec/features/create_paged_resource_spec.rb

Makes the Items table collapsible, and collapsed by default, as the "Additional Fields" set of metadata in Edit.
Should get Nick to confirm/deny last commit, hiding an empty Relationships section.
Note that this is based on ESSI-288 and should be rebased on updated master after #55 is merged.

ESSI-287: Collapsible work items

---

config/essi_config.example.yml
config/initializers/sidekiq.rb
config/sidekiq.yml

Allows Sidekiq queue names and failed job retry count to be configurable via main ESSI config file.

ESSI-385 Allows Sidekiq to be configurable via environment settings in secrets file

---

config/initializers/sidekiq.rb
config/sidekiq.yml

PR #63 introduced the ability to configure Sidekiq settings from the main ESSI configuration YAML file.  However, it wasn't until trying to run Sidekiq standalone that it was apparent that the ESSI config stash was not loaded and available when Sidekiq's default config file is parsed (`config/sidekiq.yml`)  which resulted in a runtime error (i.e. uninitialized constant ESSI)
Rather than try to figure out how to provide the ESSI config stash to that file, the Sidekiq initializer was refactored to have complete control of the assignment process and set an order of precedence.  See comments in `config/initializers/sidekiq.rb`.

Redefining how and where Sidekiq configuration values get set

---

app/helpers/lock_warning_helper.rb
app/models/concerns/extra_lockable.rb
app/models/membership_builder.rb
app/services/lock_manager_service.rb
app/views/hyrax/base/edit.html.erb
app/views/hyrax/base/file_manager.html.erb
app/views/hyrax/paged_resources/structure.html.erb
spec/helpers/lock_warning_helper.rb
spec/models/paged_resource_spec.rb
spec/services/lock_manager_service_spec.rb
spec/support/shared_examples/extra_lockable.rb

Marked WIP pending PR review.
* Adds display of lock warning into edit, structure, file manager views
* changes generation of `LockManager` to a single instance for standard use, and a single instance for `lock?` checks
* gets speedier results of `lock?` checks
Doesn't:
* doesn't add a `lock?` check into the `save_structure` action as it was already there
* doesn't modify `LockableJob`

WIP ESSI-187, UI display of locked works

---

app/actors/hyrax/actors/paged_resource_actor.rb
app/assets/javascripts/hyrax/file_manager.es6
app/forms/concerns/essi/paged_resource_form_behavior.rb
app/models/concerns/essi/paged_resource_behavior.rb
app/models/concerns/essi/paged_resource_metadata.rb
app/models/solr_document.rb
app/presenters/hyrax/paged_resource_presenter.rb
app/views/hyrax/base/_file_manager_resource_form.html.erb
spec/actors/hyrax/actors/paged_resource_actor_spec.rb
spec/models/paged_resource_spec.rb
spec/support/shared_examples/metadata_helper.rb

A PagedResource will typically have searchable text extracted during OCR derivative creation, but there will be a chance that the fidelity of the text is not high enough to make searching useful.  In these cases we will want to hide the search bar in the Universal Viewer.  
This PR adds all of the pieces needed to disable searching via a control in the File Manager toolbar.  It also adds a step in the actor to ensure that searching is enabled by default so that the option only needs to be changed in the case of wanting to disable it.  All of this is specific to the PagedResource work type.

ESSI-416 Adding ability to disable search within for a PagedResource

---

app/authorities/qa/authorities/iucat_libraries.rb
config/essi_config.example.yml
spec/authorities/qa/authorities/iucat_libraries_spec.rb
spec/services/holding_location_service_spec.rb

The ESSI config contained the full configuration value for the IUCAT holding location, which usually works even in the developer environment even though that should probably be a deployment concern.  However, when outside developers began working with the app (i.e. Notch8) the service could not be contacted and created timeout errors.  This PR disables the api configuration by default and makes the QA vocab (and specs) behave correctly when not configured.

ESSI-457 Remove IUCAT Holding Locations from ESSI config

---

app/assets/stylesheets/brand.css

First commit stabilizes against width change.
Second commit fills in the 15px margin between IU, Hyrax headers with the same background color as the Hyrax header.

ESSI-521: Stable branding header

---

app/controllers/hyrax/paged_resources_controller.rb
app/views/catalog/_index_header_list_default.html.erb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
config/initializers/blacklight_helpers.rb

Replicates functionality in Pumpkin that automatically passes search term from a results link into the UV and invokes search.  
There is new JavaScript in the Universal Viewer partial that looks for the `query` parameter and uses its value, if it exists, to invoke the UV search within.  It has logic to determine when the UV search box elements are in place before trying to act upon its selectors, which can take a variable amount of time depending on manifest building and/or caching.

ESSI-84 When navigating from search results to show page, invoke UV search with term

---

config/essi_config.example.yml

This region does not have any effect in our minio s3 service, but is necessary for Browse Everything to function due to its configuration checks.

Set any S3 region to satisfy BrowseEverything 1.0

---

app/controllers/hyrax/paged_resources_controller.rb
app/views/catalog/_index_header_list_default.html.erb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb

The previously merged PR #90 worked if accessing a PagedResource with direct URL containing a search term, but not if linking through from search results. This fixes that by refactoring parameter handling to distinguish between a catalog search term and a request for a highlighted term.

Fixing ESSI-602, failure of search term to be passed to UV

---

app/models/with_proxy_for_object.rb

This applies the same bugfix as ESSI-440, minimally.
Not included:
* Broader test coverage for logical order / structure functionality, including this change
* Any refactoring of the `LogicalOrder` stack, with regards to either/both:
* Cleaner separation of logic vs UI 
* Abandoning `ActiveFedora` persistence, and just using `JSON` persisted in `solr`

[ESSI-513] Structure editor fix for deleted FileSet, as for ESSI-440

---

Dockerfile

Per #110, Tessreact must now be at v4 to support exporting as ALTO OCR.  This PR updates the resulting image from a Docker build to install Tesseract 4.1.

Upgrading Tesseract to 4.x in the Docker build

---

app/services/essi/file_set_ocr_derivatives_service.rb
solr/config/schema.xml

This PR is technically correct with tests passing but needs group discussion to merge. It disables the `super` call back up to `Hyrax::FileSetDerivativesService.create_derivatives`, and consequently skips the MiniMagick workflows of creating thumbnails.
**Background:**
In both local and deployed environments, OCR will randomly come up missing on pages with the likelihood increasing with page count.  When ingesting one unique paged work repetitively, the affected pages and number of pages are always different, eliminating the possibility of problems with source files.
For full discussion of the multiple issues, see #118

[ESSI-648] For Consideration: Disable thumbnail creation

---

app/views/hyrax/base/_file_manager_resource_form.html.erb

Adds the same `if` check around `viewing_hint` and `viewing_direction` blocks, ensuring that form `div` is excluded if inapplicable to the given Work type.

[ESSI-742] Bugfix for File Manager render breaking for non-PR work types

---

app/controllers/concerns/essi/works_controller_behavior.rb
app/controllers/hyrax/images_controller.rb
app/controllers/hyrax/paged_resources_controller.rb

The first commit fixes the bug for Image format by moving the method definition inside the class.
The second commit makes the pertinent method available for all Work types, since the "Open large viewer" work is displayed for all Work types.

[ESSI-719] Bugfix for opening large viewer for Image format

---

config/initializers/extensions.rb

The extensions of `CollectionPresenter` and `WorkShowPresenter` were loading [Hyrax constants set to I18n lookup values](https://github.com/samvera/hyrax/blob/320512447cb48b2bfe6fb9a05b99d0fce193d810/app/models/hyrax/collection_type.rb#L12-L16), before the entire `I18n.load_path` was populated, resulting in "translation not found" results.
This PR resolves this by moving _all_ of the extension monkeypatches into an `after_initialize` callback, relocating these I18n lookups to later in the initialization sequence, after `locale` files for all the gems have been populated into `I18n.load_path`.

[ESSI-751] Move extensions initializers to after_initialize

---

app/controllers/concerns/essi/structure_behavior.rb
app/controllers/hyrax/paged_resources_controller.rb
app/presenters/concerns/essi/presents_structure.rb
app/presenters/hyrax/paged_resource_presenter.rb
app/views/hyrax/base/_show_actions.html.erb

The first commit resolves the bug by wrapping a `begin`/`rescue` block around the `link_to` for the Structure page, as an inelegant means of making it appropriately conditional.
The second commit is an optional refactor that matches the pattern for the model of having structure-related elements in an included model, in the controller and presenter.

[ESSI-688] Bugfix for linking structure path when absent

---

config/essi_config.example.yml
config/initializers/hyrax.rb

This branch along with setting up Cantaloupe as described on the wiki (https://github.com/IU-Libraries-Joint-Development/essi/wiki/1.6-Cantaloupe-Configuration) worked for me in using cantaloupe in development.

[ESSI-747] Optional Cantaloupe Configuration

---

config/initializers/extensions.rb

Fixes `/app/app/forms/hyrax/bib_record_form.rb:9:in `<class:BibRecordForm>': undefined method `primary_fields=' for Hyrax::BibRecordForm:Class (NoMethodError)`

Move primary fields outside of after init.

---

app/presenters/hyrax/paged_resource_presenter.rb

It seems [url helpers in a work presenter context need to be explicitly passed the request host](https://github.com/samvera/hyrax/blob/2.x-stable/app/presenters/hyrax/work_show_presenter.rb#L52-L56).
Resolves ESSI-790.

[ESSI-790] Add missing host parameter to search url

---

app/indexers/bib_record_indexer.rb
app/indexers/image_indexer.rb
app/indexers/scientific_indexer.rb

Revised solr indexing of the thumbnail had only been applied to the Paged Resource work type.
This applies it to the other work types.

[ESSI-759] Standardize thumbnail indexing across work types

---

config/environments/production.rb

Bulkrax JS additions broke assets:precompile in prod. This updates our config to match https://github.com/lautis/uglifier#rails

Fix assets:precompile in prod mode

---

app/actors/hyrax/actors/file_actor.rb
app/models/collection.rb
app/models/collection_branding_info.rb
app/models/file_set.rb
db/migrate/20200428144941_add_file_set_backing_to_collection_branding_info.rb
db/schema.rb
lib/extensions/extensions.rb
lib/extensions/hyrax/collection_presenter/file_set_backed_branding.rb
lib/extensions/hyrax/dashboard/collections_controller/file_set_backed_branding.rb
lib/extensions/hyrax/forms/collection_form/file_set_backed_branding.rb
spec/actors/hyrax/actors/file_actor_spec.rb
spec/controllers/hyrax/dashboard/collections_controller_spec.rb
spec/factories/collection_branding_infos.rb
spec/forms/hyrax/forms/collection_form_spec.rb
spec/models/collection_branding_info_spec.rb
spec/models/file_set_spec.rb
spec/presenters/hyrax/collection_presenter_spec.rb

Changes `CollectionBrandingInfo` from managing uploaded image files in the `/public/branding` subtree, to managing them via `FileSet` objects and retrieving their display images from the IIIF server.
The approach I took to modifying the 4 interrelated Hyrax components was to monkeypatch the controller, presenter, and form, but completely override the `CollectionBrandingInfo` model as that is changed drastically (and I originally tried it via monkeypatches, but that got messy, with the super calls.).
A few other notes:
- the `FileSet` gets created promptly as a stub and associated to the `CollectionbrandingInfo`, but its fleshing out is handled by the actor/job stack, so the images may not actually show up for awhile, until that process has completed.
- `CollectionbrandingInfo` will update …

[ESSI-704] Move branding files to FileSet backing

---

app/helpers/catalog_helper.rb
app/indexers/concerns/essi/iiif_collection_thumbnail_behavior.rb
app/services/iiif_collection_thumbnail_path_service.rb
lib/extensions/extensions.rb

The first commit uses IIIF Thumbnails for both collection types (User Collections, Admin Sets), as is already done for works.
The second one tweaks `#thumbnail_url` logic in `CatalogHelper`, but I'm less confident it's the right change.  The overall context for this, is: Hyrax uses a mix of two paradigms for displaying thumbnails:
* **Blacklight-based**, doing a `render_thumbnail_tag` call on a `SolrDocument` _document_ record
* **Presenter-based**, calling `thumbnail_path` on the _presenter_
This is why, for objects with no `thumbnail_id`, we got a mix of the `default.png` display of a dogeared page (when using the Blacklight methodology) that's agnostic of the object's class, versus displaying generic 'work.png' (a single box) or 'collection.png' (a stack of 3 boxes) -- the indexers for …

[ESSI-822] Revise collection thumbnails

---

app/controllers/concerns/essi/remote_metadata_lookup_behavior.rb
app/models/remote_record.rb
config/locales/en.yml
lib/iu_metadata/client.rb
spec/fixtures/marc_VAD5427.xml
spec/fixtures/mods_VAD5427.xml
spec/fixtures/vcr_cassettes/bibdata.yml
spec/fixtures/vcr_cassettes/marc_VAD5427.yml
spec/fixtures/vcr_cassettes/mods_VAD5427.yml
spec/fixtures/vcr_cassettes/mods_deadbeef.yml
spec/iu_metadata/client_spec.rb
spec/support/shared_examples/remote_metadata.rb

The remote source metadata logic we pulled from pumpkin was missing error handling for two cases:
* supplying an invalid `source_metadata_identifier`
* attempting to pull remote metadata and getting no results for the identifier
This PR handles both cases, but whereas in pumpkin these cases blocked saving the work and flashed a _failure_ message to the user, in ESSI both cases succeed and merely flash an _alert_ to the user.  The validation logic for a `source_metadata_identifier` is also loosened to allow periods and hyphens.

[ESSI-831] Turn source_metadata_identifier errors into alerts

---

app/actors/essi/actors/perform_later_actor.rb
app/jobs/perform_later_actor_job.rb
spec/actors/essi/actors/perform_later_actor_spec.rb
spec/jobs/perform_later_actor_job_spec.rb
spec/support/shared_examples/remote_metadata.rb

Sends calls to the actor stack update and destroy methods to sidekiq for async processing.

Essi-830 Enable update/destroy in PerformLaterActor

---

Dockerfile
docker-compose.yml

This uses the debian buster image as the base for the essi docker image. Previously it was pinned to stretch because IU CAS SSL was incompatible.
This also adds an enhancement to the dev docker compose stack that saves the rails application cache between restarts.

Essi-357 Use buster docker image, save dev rails cache 

---

.env
app/controllers/hyrax/paged_resources_controller.rb
app/presenters/hyrax/paged_resource_presenter.rb
config/essi_config.docker.yml
config/essi_config.example.yml
spec/presenters/hyrax/paged_resource_presenter_spec.rb

Add a setting to the ESSI config to turn on/off pdf downloads
Make sure current user is admin before showing pdf download button
Pull Request https://github.com/IU-Libraries-Joint-Development/essi/pull/184 must be merged before this PR
Both conditions met:
One or both conditions not met:

Essi 913 pdf download setting

---

Dockerfile

Our Dockerfile is based on Debian Buster which currently has tesseract 4.0 available, however ALTO support was added in 4.1 which is still in testing for Debian. This adds an external package source that gets packages from the Debian package maintainer's own website. 
Once Tesseract 4.1 is added to Buster this commit can be reverted.

ESSI-970 Use external repo for tesseract 4.1

---

app/controllers/hyrax/paged_resources_controller.rb
app/models/ability.rb
app/presenters/hyrax/paged_resource_presenter.rb

Non admin users should be able to download pdf when flag is set to true. This ended up being a permissions issue and needed pdf added to the ability file. + Error handling.

hot fix: non admin users should be able to download pdf if setting is true

---

app/actors/hyrax/actors/file_actor.rb
app/models/file_set.rb
config/essi_config.docker.yml
config/essi_config.example.yml
lib/extensions/extensions.rb
spec/actors/hyrax/actors/file_actor_spec.rb

Some notes:
* I took out the kakadu Docker stuff, and [stashed it in a gist](https://gist.github.com/aploshay/10e4fa4c410c00577bd9b80b7b70f6a4).
* The ingest logic now attempts to infer the `source_metadata_identifier` value from a `FileSet` from the uploaded filename
* This also includes a change to the logic on storing a link to preservation masters -- whether to do it, and how.  
* Previously, this was an either/or against the config value for `store_original_files` -- now, it looks at whether a value is present for `master_file_service_url`, and infers the presence of a value to indicate storing a link to masters.  Consequences are:
* You'll get empty `FileSet` objects unless you set at _least_ one of `store_original_files`, `master_file_service_url`; presumably you don't want that, …

[ESSI-761] Apply jp2 image conversion, if configured

---

config/initializers/derivatives_source_file_service.rb
config/initializers/extend_file_set_derivatives.rb
lib/extensions/extensions.rb

Curiously, when I run the current `master` locally via `docker-compose`, I'm finding inconsistent results on whether some settings modified in `config/initializers` files take effect _at all_, or only in console, accessed via:
`docker-compose exec essi bash`
`rails c`
versus the running instance, when entering the same evaluations through `byebug` after catching a debugger statement, in either of:
`docker attach essi_essi_1 # for debugger statements in views, other application code`
`docker attach essi_worker_1 # for debugger statements in Jobs`
I do not find the same differences when each piece of the stack is run locally, directly.
What got me looking at this was seeing that OCR derivation wasn't running, despite it being configured to do so.
Here are the 3 things I've noticed, the …

[ESSI-1013] [ESSI-1034] Drop, move configuration initializations

---

app/assets/stylesheets/brand_tweaks.css

Remove the margin-top in footer css. This change will remove the blank space in between mahogany pre-footer bottom and crimson line above IU footer

ESSI-1081 Remove blank space between pre-footer and IU footer

---

app/services/iiif_thumbnail_path_service.rb

Prevents an exception being raised when indexing a Fileset that doesn't have an original_file associated with it (yet).

Return nil when original_file is not available

---

lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb

A more elegant solution would be presenter method calls that are context-aware of displaying in the general UI vs. within universal viewer, but that would require deeper changes to the Hyrax pattern.  So, it ain't pretty, but it works.

[ESSI-1161] Remove HTML elements for UV metadata

---

app/controllers/concerns/essi/structure_behavior.rb
spec/controllers/hyrax/archival_materials_controller_spec.rb
spec/controllers/hyrax/paged_resources_controller_spec.rb
spec/support/shared_examples/paged_structured_controller.rb

Currently, trying to load a structure page when not logged in just produces a ruby error.  This does a proper login redirect.

Add authorize calls to #structure, #save_structure

---

app/assets/stylesheets/digital_collections/_layout.scss
app/views/hyrax/my/_search_form.html.erb

Turns out we had effectively disabled the search form label awhile back; this turns it to sr-only

ESSI-1180 Search form accessibility

---

app/views/hyrax/homepage/_home_content.html.erb

According to the accessibility document, it is good to add role="tablist" in ul tag and role="tab" in li tag. I made the change according to that.

ESSI-1179 more accessible behavior on the homepage/add role=tablist

---

lib/iu_metadata/final_redirect_url.rb

Upstream gem this is based on ignores port when building a uri string. This uses URI to_s instead.

Fix port missing from final url

---

Gemfile
Gemfile.lock
config/essi_config.docker.yml
config/essi_config.example.yml
config/initializers/airbrake.rb

Installs the airbrake gem and adds empty project_id and project_key config stubs.
Rails errors that occur in development mode (with cache_classes and/or eager_load disabled) seem to not be reported as errors to the Airbrake dashboard. Errors in sidekiq are reported.
It is expected that errors in production mode will be reported.

ESSI-1190 Airbrake gem installed with config stub

---

app/models/hyrax/contact_form.rb
app/views/_controls.html.erb
app/views/hyrax/contact_form/new.html.erb
config/locales/hyrax.en.yml

Removes Help tab, tweaks content of Contact page.
This required overriding stock Hyrax code, when I felt like it mostly should have been doable solely via config changes.  I opened up corresponding PRs in Hyrax to this effect: [#4720](https://github.com/samvera/hyrax/pull/4720), [#4721](https://github.com/samvera/hyrax/pull/4721)

ESSI-1197: Help and Contact page changes

---

app/views/hyrax/base/_show_actions.html.erb

Corrects a bug in logic that hides edit action buttons  if `site_usage == access_only` and additionally hides the remaining left side buttons for adding to collection and adding as featured item.

ESSI-1230 Hiding all action buttons for works when site usage is access only

---

app/views/shared/_ajax_modal.html.erb

The error is due to aria-labelledby tag in "_ajax_model.html.erb'. After look into the code and check the hyrax. The file does not necessarily override. The origin "ajax_modal.html.erb' is from /gems/ruby-2.6.3/gems//blacklight-6.24.0/app/views/shared/_ajax_modal.html.erb and does not have aria-labelledby tag there.  So I think the better solution would be removing the whole file.

ESSI-1226 accessibility broken aria reference

---

lib/extensions/bulkrax/object_factory/structure.rb
spec/models/bulkrax/object_factory_spec.rb

Changes to the customization of `Bulkrax::ObjectFactory#permitted_attributes`:
* Fixes `super` call to retain Bulkrax-added fields to the work class properties (including `visibility`)
* Adds `admin_set_id` to added fields -- this was missing in bulkrax, and raised as [bulkrax issue 271](https://github.com/samvera-labs/bulkrax/issues/271)
* Adds spec coverage

[ESSI-1153] [ESSI-1256] Pass all bulkrax importer form fields to work

---

app/views/catalog/_index_list_default.html.erb

Resolves:
DEPRECATION WARNING: You provided a String value to IndexPresenter#field_value Provide a Blacklight::Configuration::Field instead. This behavior is deprecated in Blacklight 7.

Resolve deprecation warning for #field_value calls

---

lib/extensions/bulkrax/entry/allinson_flex_fields.rb
lib/extensions/extensions.rb

It seems the bulkrax importer isn't guaranteed to have loaded the Allinson flex properties for the work class being imported, but that generating at least one instance ensures it.

[ESSI-1153] [ESSI-1265] Ensure Bulkrax loads Allinson flex properties

---

app/services/ocr_runner.rb
app/services/processors.rb

There are 2 known errors to occur inconsistently and intermittently when a `CreateDerivativesJob` is spun off by a `Bulkrax::ImportJob`:
**NameError**
This results from an (inconsistent) attempt to load `OCRRunner::Processors` instead of `Processors`
The PR attempts to block the namespacing with an initial `::`
**LoadError**
Intermittently, you'll see an error something like:
`LoadError (Unable to autoload constant Processors::OCR, app/services/processors/ocr.rb to define it)`
which is a bit odd because that file is present, and does define it.
This change is more heavily experimental and unproven as a remedy, but it looks like this may be something going awry with autoloading or eager-loading, and explicitly making an (empty) `Processors` module _may_ help here.
These changes are all …

[ESSI-1221] Attempt to prevent Processors::OCR LoadError, NameError

---

app/actors/essi/actors/create_with_remote_files_ordered_members_structure_actor.rb
app/models/bulkrax/mets_xml_entry.rb
app/models/mets_document.rb
config/essi_config.docker.yml
config/essi_config.example.yml
config/initializers/hyrax.rb
lib/extensions/extensions.rb
spec/iu_metadata/mets_record_spec.rb

1st commit gets Bulkrax METS ingest to fully process images:
* all remotely sourced (https://...), with structure
* all locally sourced (as direct file paths, like "/path/to/file"), but loses structure
* from a combination of remote and local sources, but loses structure
The structure loss with local files looks like it's due to us handling structure entirely in the `CreateWithRemoteFiles` version of the actor, and not at all in the `CreateWithFiles` version.  It should be pretty straightforward to add structure support to the other actor, but handling a mixed-source case would be trickier as the current structure-file map generation logic is dependent on all the files being handled in the same actor.
An important note here is that handling files as raw paths works, but going that route, …

[ESSI-1221] Bulkrax METS ingest, processing local/remote images

---

app/views/shared/_citations.html.erb

Turns out the Hyrax citations partial raises a ruby-level error if no rights_statement is available; this fixes it to gracefully render when that field is absent or empty

[ESSI-1258] Rights statement rendering, when missing

---

app/actors/concerns/essi/apply_ocr.rb

Currently the config flag for `index_ocr_files` hard-sets ocr_state to "searchable", even if it's already been set to another value (though the manual creation form, or Bulkrax import parsing of CSV/METS/etc.)  This changes it to a soft set, only if blank.

At work creation, keep existing ocr_state value if present

---

Gemfile
Gemfile.lock
config/initializers/okcomputer.rb
lib/essi_dev_ops/fcrepo_check.rb
lib/essi_dev_ops/sidekiq_process_check.rb

Adds the okcomputer gem and custom repository service checks.  **Note:** For this to be available in the application, there must be a configuration section in the main YAML config file.  It is being omitted from the committed config files so that a route for okcomputer is not defined by default in any given deployment. Configuration should look something like:
```
okcomputer:
mount_at: '/status'
user: user
password: password
```

Adding okcomputer and custom service checks

---

Gemfile.lock
app/controllers/catalog_controller.rb
app/indexers/essi/file_set_indexer.rb
solr/conf/schema.xml

Allows for flexible searching of *_tesim fields. Requires solr config change and reindexing.
OCR text fields are renamed to avoid being included in all_text.
Explicitly add abstract as a searched field for when it is used instead of description.
Fix word_boundary reference
Update solr_wrapper gem.

ESSI-1313 Enable all_text_timv in solr schema

---

config/environments/development.rb
config/environments/production.rb
config/essi_config.docker.yml
config/essi_config.example.yml
config/initializers/hyrax.rb

* Explicitly disables mailer errors in production
* Adds configuration for SMTP settings
* Adds configuration for `contact_email`, the email address sent to by the Contact form

[ESSI-1316] Turn off production mail errors; add config for contact_email, SMTP

---

config/environments/development.rb
config/environments/production.rb
config/essi_config.example.yml

To get email to route out of container environments and to a SMTP server, different environments may need more control over the available Action Mailer options.

ESSI-1316 Making additional SMTP options configurable

---

app/models/bulkrax/mets_xml_entry.rb
app/views/bulkrax/importers/_mets_xml_fields.html.erb
lib/extensions/extensions.rb
lib/extensions/hyrax/select_type_list_presenter/options_for_select.rb
spec/presenters/hyrax/select_type_list_presenter.rb

For METS format, changes Bulkrax format to pull work type from user form, rather than from METS metadata.
Another solution might be to handle this as rights_statement is done -- pulling the value from the metadata, but defaulting to the form value when blank, with a checkbox option to enforce overriding with the form value -- but this is minimal change necessary.

[ESSI-1157] Add work type selection to Bulkrax import form for METS

---

lib/extensions/allinson_flex/prepend_profiles_controller.rb
lib/extensions/allinson_flex_extensions.rb
spec/controllers/allinson_flex/profiles_controller_spec.rb
spec/factories/allinson_flex/profiles.rb
spec/fixtures/allinson_flex/yaml_example.yaml

Modified the #import action on the AllinsonFlex profiles controller to catch ruby error conditions for:
* invalid YAML
* valid YAML, but with invalid data (according to the flexible metadata schema)

[ESSI-1338] Provide UI feedback for failed metadata profile import

---

app/actors/allinson_flex/dynamic_schema_actor.rb
app/helpers/bulkrax/importers_helper.rb
app/views/bulkrax/importers/_csv_fields.html.erb
app/views/bulkrax/importers/_mets_xml_fields.html.erb
lib/extensions/bulkrax/entry/dynamic_schema_field.rb
lib/extensions/bulkrax/object_factory/create_with_dynamic_schema.rb
lib/extensions/bulkrax/object_factory/structure.rb
lib/extensions/extensions.rb

For Bulkrax import via METS and CSV formats, add a form selection for "Profile Version".  The imported works should use the chosen Profile version, rather than assuming the most current version.  For CSV, the importer form selection can be overridden for one or more specific rows by providing `profile_id`/`profile_version` -- you can also provide the `dynamic_schema_id` directly but that value has much less discoverability.

[ESSI-1336] Bulkrax import: use a specified dynamic schema (when provided)

---

config/initializers/hyrax.rb
config/locales/hyrax.en.yml

The value to be changed needs to be tackled in 3 distinct manners:
1. Persistence in `Hyrax::CollectionType`, which can be fixed with a database record update along these lines:
```ruby
user_collection = Hyrax::CollectionType.find_by_machine_id('user_collection')
user_collection.update_attribute(:description, 'A Collection can be created by any user to organize their works.')
user_collection.update_attribute(:title, 'Collection')
```
(this PR does _not_ currently include that as a migration, but it could be added)
2. Certain `I18n` config values; there are separate commits explicitly inheriting these from hyrax, and then modifying them
3.  A hyrax issue is that:
* certain `I18n` values are read and frozen during class initialization -- see [an …

[ESSI-1358] Change "User Collection" to "Collection"

---

app/indexers/archival_material_indexer.rb
app/indexers/bib_record_indexer.rb
app/indexers/concerns/essi/indexes_filesets.rb
app/indexers/image_indexer.rb
app/indexers/paged_resource_indexer.rb
app/indexers/scientific_indexer.rb
lib/extensions/extensions.rb
lib/extensions/hyrax/collection_member_search_builder/rows.rb
lib/extensions/hyrax/collections/collection_member_service/available_member_fileset_title_ids.rb
lib/extensions/hyrax/forms/collection_form/all_files_with_access.rb

Inherited issues:
* default limit of 10 rows in a solr query result (unless otherwise specified)
* `SearchBuilder` and subclasses limit of 100 rows in a solr query result (even if a greater amount specified)
* poorly-scaling performance of `#all_files_with_access` generating a tree of presenters and solr queries
Changes:
* adds support for `CollectionMemberSearchBuilder` returning any configured number of rows
* refactors #all_files_with_access to run a single solr query
* adds indexing of `FileSet` titles to a work, along with ids
*  This is more consistent with how collections associated to a work are indexed on the work for both titles and ids, and facilitates the `#all_files_with_access` refactoring

[ESSI-1361] Allow choosing Collection thumbnail from any Fileset (beyond first 10)

---

app/controllers/catalog_controller.rb
app/views/catalog/_index_list_default.html.erb
app/views/hyrax/base/_attribute_rows.html.erb

Changes here to later be reverted by ESSI-1321, which will make non-admin property visibility configurable instead of hard-coded.

[ESSI-1322] Hide certain fields from non-admin display via blacklight

---

Gemfile
Gemfile.lock
app/helpers/file_manager_helper.rb
app/models/solr_document.rb
app/views/hyrax/base/_file_manager_attributes.html.erb
lib/extensions/extensions.rb
lib/extensions/hyrax/file_set_presenter/extracted_text.rb
lib/extensions/hyrax/forms/work_form/work_members_speedy.rb

Loading the edit form for works with many filesets can be very slow, to the point of the web proxy timing out. Rendering the edit form loads from fedora all members of the work, both filesets and works, and then filters to only works. This PR changes the loading behavior to use the membership data indexed in solr.
The work file manager shows icons for each file indicating if there is an associated OCR file. This required a fedora lookup for each file. This is being changed to use the ocr_text solr field.
This also adds some profiling gems to the development gem group. Now, when in development mode, we should see a profiler dialog in the upper left of the screen. A stack profile for a particular page can be accessed by adding `pp=flamegraph` to the page url parameters.

Essi-1329 Speedup work edit forms

---

app/helpers/application_helper.rb
app/services/allinson_flex/dynamic_schema_service.rb
app/views/records/edit_fields/_allow_pdf_download.html.erb
app/views/records/edit_fields/_campus.html.erb
app/views/records/edit_fields/_default.html.erb
app/views/records/edit_fields/_holding_location.html.erb
app/views/records/edit_fields/_source_metadata_identifier.html.erb
app/views/records/edit_fields/_viewing_direction.html.erb
app/views/records/edit_fields/_viewing_hint.html.erb
lib/extensions/allinson_flex/include_allinson_flex_constructor.rb
lib/extensions/allinson_flex_extensions.rb
spec/features/create_archival_material_spec.rb
spec/features/create_bib_record_spec.rb
spec/features/create_paged_resource_spec.rb
spec/fixtures/vcr_cassettes/iucat_libraries_up.yml
spec/helpers/application_helper_spec.rb

Displays any provided usage_guidelines text configured in allinson_flex, both in cases where no help text is otherwise present, or where default help text is otherwise displayed.
Replacement for PR #330

 [ESSI-1382] Pull edit from hint text from usage_guidlines in allinson_flex 

---

app/views/bulkrax/exporters/_form.html.erb
config/locales/bulkrax.en.yml
db/migrate/20210820144015_add_make_round_trippable_to_bulkrax_exporters.rb
db/schema.rb
lib/extensions/bulkrax/entry/optional_round_trippable_save.rb
lib/extensions/bulkrax/exporters_controller/support_make_round_trippable.rb
lib/extensions/extensions.rb

Bulkrax export saves each record it exports, setting the `source` field to include the object's `id` value, to support round-tripping.  This slows down the export process results in server response timeout.
The first two commits add a check to only perform the save when the `source` does not yet contain the desired value.  This would improve the performance on subsequent exports of the same records, skipping unnecessary `save` calls.
The later commits add a new flag to the exporter object, form, and controller to allow opting out of the save calls, if the ability to round-trip is not needed.

[ESSI-1371] In bulkrax export, skip redundant record saves, and make optional

---

config/essi_config.example.yml
config/initializers/okcomputer.rb

The OKComputer status endpoint currently registers a check for Sidekiq processes running locally.  There are appropriate cases where we don't run Sidekiq attached to the local Rails environment, like in the public access site, or when we want to distribute job processing to other servers.  To prevent the status check from returning as failed in these cases, this PR adds and checks for a boolean specifying whether jobs processing is local or not:
```
sidekiq:
processes_locally: true
queue_names:
...
```

ESSI-1414: Provide option to disable Sidekiq status check

---

app/jobs/application_job.rb
app/jobs/bag_work_job.rb
app/jobs/characterize_job.rb
app/jobs/ingest_yaml_job.rb
app/jobs/perform_later_actor_job.rb
app/jobs/save_structure_job.rb
config/essi_config.docker.yml
spec/jobs/application_job_spec.rb
spec/jobs/application_job_spec_spec.rb

Attempts to change the behavior of all jobs based on ApplicationJob to wait to enqueue new jobs until the current job has completed performing. This uses thread local variables to store the new jobs until an after hook completes the enqueueing.
Doing this helps avoid race conditions where the repository objects in memory in the primary import job thread do not match what has been written to active fedora by secondary jobs (e.g characterization, derivatives, etc).
Thanks to `Hyrax::ApplicationJob`, all jobs should now make use of this behavior including those contained within the hyrax gem.

Essi-1323 Sequential job enqueueing

---

.circleci/config.yml
Dockerfile

By default FITS uses Apache Tika as one of its tools, which in turn will run tesseract. As far as I can tell, no data from running tesseract in this way makes it into the repository. Other Samvera projects have disabled Tika in the same way as this PR, by commenting the relevant line out in the FITS configuration file. Our own tesseract OCR service should be unaffected.

essi-1441 Disable FITS use of tesseract via apache tika

---

app/controllers/catalog_controller.rb
app/controllers/concerns/essi/dynamic_catalog_behavior.rb
app/services/allinson_flex/dynamic_schema_service.rb
app/views/hyrax/admin/admin_sets/_form_metadata.html.erb
app/views/hyrax/base/_attribute_rows.html.erb
config/locales/hyrax.en.yml
config/m3_json_schemas/856237c2c6c64385619a643c88138fc5a776f7a8/m3_json_schema.json
lib/extensions/allinson_flex/include_profile_property.rb
lib/extensions/allinson_flex_extensions.rb

In the "Indexing" section of an AllinsonFlex profile, adds a new "admin_only" option.  When applied in conjunction with other values, it adds an admin_only check:
* `facetable`: this indexes and displays a facet; adding "admin_only" now adds an admin_only user check to display the facet
* `stored_searchable`: this indexes the field and displays it in catalog results and the work show page; adding "admin_only" now adds an admin_only user check to display the field in the catalog results and work show page
Although the changes are now more appropriately under ESSI-1384 after tweaking the division of work between the stories, this also resolves a couple of issues on the Metadata Context tab editing an AdminSet:
* supplies missing translations for page_description and …

[ESSI-1321] In an AllinsonFlex profile, edit property visibility (with an admin_only check)

---

app/jobs/bulkrax/application_job.rb
app/jobs/concerns/sequential_job.rb

Bulkrax jobs are based on a different (Bulkrax::)ApplicationJob class than essi's ApplicationJob. This cause them to not use the sequential job enqueuing system. This PR moves that system to a module and overrides Bulkrax::ApplicationJob which was previously empty anyways.

ESSI-1474 Move sequential job queueing to module so bulkrax can use it

---

.circleci/config.yml

The circleci base images updated to node 16 which seems to be incompatible. This gets us back to node 12, although we do need to plan to upgrade soon due to EOL.

Use a non-node ci image since we install node 12 ourselves

---

app/controllers/purl_controller.rb
config/context.yml
config/metadata_profile/essi_short.yaml
lib/iu_metadata/marc_record.rb
spec/controllers/purl_controller_spec.rb

PurlController changes:
* Add support for ArchivalMaterial
* changes purl lookup field from "identifier" to "purl"
Remote metadata lookup changes:
* changes identifier lookup to purl lookup
Note that testing, and working in deployment, requires configuring a "purl" field in allinson_flex with this URI:
http://purl.org/dc/elements/1.1/identifier

[ESSI-1470] Update PurlController to handle all worktypes

---

Dockerfile

Fixes `SystemStackError: stack level too deep` exceptions when saving structure in large works.
The cause of this is the recursive method `ActiveTriples::ExtendedBoundedDescription#each_statement` which recurses once for each part of a logical_order (our structure object in Fedora). Each recursion loop adds 27 method calls to the ruby stack which quickly exceeds the default stack size limit of 1048576. For example, a work with 241 pages required this setting to be set to at least 1645000 (+-5000) to succeed.
The new value was selected based on it being an alternate default value when using a memory sanitizer, so in theory it's not egregiously oversized. See https://github.com/ruby/ruby/blob/ruby_2_7/vm_core.h#L693
If further stack size limits are encountered, there are three other stack …

ESSI-1503 Increase ruby stack size limit

---

package.json
yarn.lock

Remove shx dependency to fix asset precompilation. Same change is in hyrax 3.

essi-1518 Remove shx dependency to fix asset precompilation

---

app/views/bulkrax/exporters/show.html.erb

It looks like in our change from bulkrax 1.0.0 to 1.0.2 a few months ago, there was a change to how 'collections' is parsed and stored that broke a view.  This attempts to work around the issue by differentially displaying the value.
Display is broken for both exporters currently up on the dev server.  Locally, I am finding display of some exporters works, others are broken, but this change resolves them all.  To test this locally, you may need to create an exporter if you currently have none.

[ESSI-1370] bulkrax export display

---

docker-compose.yml

Updates docker compose to use Cantaloupe 4.1.11 and with the workaround for low bit depth images applied. Also corrects a typo in the configuration env variables so that OpenJpeg is the processor used. The Kakadu processor is no longer available.

ESSI-1527 Update docker-compose cantaloupe to 4.1.11, fix config typo

---

.circleci/config.yml
Dockerfile

Upgrading from ruby 2.7.4 to 2.7.5 should not, in principle, break the stack.  But, it does.
In the future, this might be resolved in updates to the affected gems, or with ruby 2.7.6.
But for the moment, holding back to 2.7.4 keeps the build working.

[ESSI-1542] Fix CircleCI builds with ruby holdback

---

lib/extensions/hyrax/forms/collection_form/customized_terms.rb

Minor change to expose the `source` field in the UI, for a Collection.  This is the default field used for Bulkrax import/export record-matching -- but even if we configure using a different field, or don't use Bulkrax for import/export, it's probably better to expose this field than hide it.  Note this change exposes the field on the edit page, but not on the show page -- the same view partial is used for both admin and public views, and we probably don't want to clutter the public view with this field.

[ESSI-1480] Expose :source in Collection edit page

---

app/indexers/archival_material_indexer.rb
app/indexers/bib_record_indexer.rb
app/indexers/essi/dynamic_indexer_behavior.rb
app/indexers/image_indexer.rb
app/indexers/paged_resource_indexer.rb
app/indexers/scientific_indexer.rb
spec/services/cover_page_generator.rb
spec/services/essi/generate_pdf_service_spec.rb

The default indexing process returns an `Array` for multi-valued field values, in a `#to_solr` call:
https://github.com/samvera/active_fedora/blob/12.2-stable/lib/active_fedora/indexing_service.rb#L30-L65
https://github.com/samvera/active_fedora/blob/12.2-stable/lib/active_fedora/rdf/indexing_service.rb#L21-L83
However, the dynamic indexing from `allinson_flex` pulls values directly from the resource:
https://github.com/IU-Libraries-Joint-Development/allinson_flex/blob/f3ed44ff96d50bc7c42cf2b9693d9b081f9a2f0c/app/indexers/allinson_flex/dynamic_indexer_behavior.rb#L20
which results in a value type of
```rb
ActiveTriples::Relation
```
instead.
If this is saved to `Solr`, it is ultimately persisted as an `Array` -- and that's what we get back from a `Solr` search, and all is well.  But if …

[ESSI-1539] tweak dynamic indexing

---

app/controllers/concerns/essi/pdf_download.rb
app/controllers/hyrax/archival_materials_controller.rb
app/controllers/hyrax/paged_resources_controller.rb
app/models/archival_material.rb
app/models/concerns/essi/ocr_behavior.rb
app/models/concerns/essi/pdf_behavior.rb
app/models/concerns/essi/pdf_metadata.rb
app/models/paged_resource.rb
app/models/solr_document.rb
app/presenters/concerns/essi/presents_pdf.rb
app/presenters/hyrax/archival_material_presenter.rb
app/presenters/hyrax/paged_resource_presenter.rb
app/views/records/edit_fields/_pdf_state.html.erb
config/metadata_profile/essi_short.yaml
spec/presenters/hyrax/archival_material_presenter_spec.rb
spec/presenters/hyrax/paged_resource_presenter_spec.rb
spec/support/shared_examples/pdf_sequence_rendering.rb

Various changes:
* Moves shared Presenter code into a module, and shared Presenter spec code into a shared_example
* Changes the paradigm for the pdf download Boolean to match the pattern we're using for ocr_state/ocr_searchable
* replaces allow_pdf_download with pdf_state (ActiveFedora property) and pdf_downloadable (solr index)
* pdf_state is present in the minimal default metadata profile, but the property is not hard-coded, rather expected to be configured via allinson_flex
* adds a custom UI component to present pdf_state values ("downloadable", "disabled") as a true/false radio button
For this to work, there needs to be a pdf_state property configured in allinson_flex, as follows:
**key**: pdf_state
**display_label**: (probably "PDF Download" or something similar)
**available_on**: …

[ESSI-1540] Bugfix and refactoring for allowing PDF download

---

lib/extensions/active_fedora/file/escaping_obsoletions.rb
lib/extensions/extensions.rb
lib/extensions/hydra/access_controls/permission/escaping_obsoletions.rb

A couple pieces of the hyrax stack are calling obsolete URI.encode, URI.decode methods that clutter add tons of clutter to test output and server logs.  This is a proposal for monkeypatching around them.

Escaping obsoletions

---

app/actors/essi/actors/perform_later_actor.rb
lib/extensions/allinson_flex/prepend_work_dynamic_schema.rb

Background context: we earlier applied bugfixes for some allinson_flex issues (61, 63), one of which was an object was _always_ loading the newest dynamic schema, even when it wasn't supposed to.  But it looks like in fixing that, we've needed to address actively loading the newest schema when we _are_ intending to upgrade to it.
Running main locally, I find I can break updating a work under these circumstances:
* Have an existing work, using the newest metadata profile version
* Create a new metadata profile version with a new property
* Edit the work, assigning a value to a new property, and save
I find that the work is not updated, and although the UI shows no complaints, the server logs show the actor/job stack errored out trying to handle the new attribute that's not in the older …

Modify PerformLaterActor to move work to newest schema on #update

---

Gemfile
app/controllers/application_controller.rb

Activates the rack-mini-profiler gem in production and restricts access to admins. rack-mini-profiler disables some cache related headers, so there may be an impact on performance.

Load profiler gems in prod, restrict to admins

---

app/controllers/concerns/essi/dynamic_catalog_behavior.rb

Eager loads profile properties and their texts to avoid querying the db thousands of times.

Optimize profile property text loading to avoid N+1 db queries

---

app/services/holding_location_service.rb

The holding location web service is being queried for every work on a search results page, which adds a second or two to the response time when all 10 results have a holding location.
This caches the web service response for between 1-2 hours.

Cache data from holding location service

---

app/models/concerns/essi/dynamic_solr_document.rb

The AllinsonFlex DynamicSolrDocument is loading the profile and (re)defining attributes every time a SolrDocument instance is initialized. On pages with multiple objects this incurs a large performance penalty. For example, the All Collections Dashboard test case would spend ~80% of its time in this method.
This loading only needs to happen once per request, but because the outcome is defining methods, the effect of loading should persist even after the request is finished.

ESSI-1554 Load AllinsonFlex attributes only when needed

---

app/models/user.rb
config/environments/test.rb
spec/models/user_spec.rb

Calling `admin?` on a user currently regenerates the user's ldap membership list. Some metadata fields now check admin status causing repeated lookups to render a single page. This change caches that result. The cache entry will be invalidated by a change to the user record, which should happen when logging in.

Cache user ldap roles to speed up user.admin?

---

app/controllers/concerns/essi/pdf_download.rb
app/controllers/concerns/essi/works_controller_behavior.rb

Turns out [stock hyrax 2.9.6 does an object load and authorization for most actions](https://github.com/samvera/hyrax/blob/v2.9.6/app/controllers/concerns/hyrax/works_controller_behavior.rb#L27-L31), which we don't want for #pdf (for those PDFs that are available for public download).  And we probably do want it for #file_manager, since calling it without being logged in produces a ruby error.

[ESSI-1540] Remove authorization for #pdf, add for #file_manager

---

app/views/catalog/_index_header_list_default.html.erb
config/initializers/blacklight_helpers.rb

An earlier PR added functionality to pass along a search term through catalog results, to the individual work display, to be applied in UV for search term highlighting:
https://github.com/IU-Libraries-Joint-Development/essi/pull/90
It looks like there's been some gem drift in the meantime that broke our monkeypatch.  The PR fixes the monkeypatch, which should resolve the ruby errors that can currently be generated in "gallery" and "masonry" view for catalog results that include Collections.
The second commit adds the text query pass-through feature to the catalog results "list" view, where it was missing.

[ESSI-1562] Fix catalog "masonry" and "gallery" views with query parameter, add to "list" view

---

app/assets/javascripts/browse_everything/behavior.js
spec/features/csv_importer_spec.rb
spec/support/capybara.rb

Optimizes how Browse Everything uses the DOM to track which files are selected.
Selecting 12000 files can now be done in under a minute, from opening of dialog to submitting the form, where previously it took ~10 minutes just to select the files in a directory.
Once we update the browse-everything gem to a version that has this fix (> 1.1.2?), this file should be removed.

Essi-1545 Browse Everything optimized

---

app/controllers/application_controller.rb
config/routes.rb

Going to a missing page or unknown format is usually just a 404 sent to the client. Raising an exception and airbrake notice seems unnecessary.
Based on the new CircleCI config branch.

ESSI-1576 Quiet route errors

---

app/models/ability.rb
app/views/hyrax/dashboard/sidebar/_activity.html.erb
config/routes.rb

Add a Sidekiq dashboard link to the hyrax dashboard. Only visible to admins, which is now checked via the user's abilities to allow other user types to potentially access it in the future, if needed.
Note to devs: I could not find a route helper (e.g. sidekiq_web.root_path) so had to use a string instead.
Based on the new CircleCI config branch.

ESSI-1577 Sidekiq dashboard link

---

lib/extensions/qa/authorities/collections/collections_search.rb
spec/authorities/qa/authorities/collections_spec.rb
spec/factories/object_id.rb

Adds an * to the query used to search for collections when adding a collection or work to a collection.
The collection factory for the specs depends on another factory that we had not yet copied in from hyrax.
Based on the new CircleCI config.

Essi-1520 Collection wildcard search

---

config/essi_config.docker.yml
config/essi_config.example.yml
lib/iu_metadata/client.rb
spec/fixtures/vcr_cassettes/bibdata.yml
spec/fixtures/vcr_cassettes/marc_VAD5427.yml
spec/fixtures/vcr_cassettes/mods_VAD5427.yml
spec/fixtures/vcr_cassettes/mods_deadbeef.yml

Changes the yazproxy call to use a configurable value, instead of a hardcoded one.
(The committed value does need to be changed to a working one, in deployment, through a config change.)
TBD: enable or deprecate the "see_also_hash"
Also, see equivalent pumpkin PR:
https://github.com/IU-Libraries-Joint-Development/pumpkin/pull/218

Update config for yaz proxy

---

app/views/_user_util_links.html.erb
app/views/users/sessions/log_in_as.html.erb
config/essi_config.docker.yml
config/essi_config.example.yml
config/initializers/switch_user.rb

If configured to "true" for local development, allows direct access to switch_user without first logging in.
(_Not_ tagging this for configuration change, since we don't need or want any configuration change on the servers.)

Configurable switch_user in development without login

---

Gemfile.lock
package.json
yarn.lock

In draft status pending merging of [prerequisite allinson_flex PR](https://github.com/IU-Libraries-Joint-Development/allinson_flex/pull/6), then adding to this PR a bundle update to use the updated allinson_flex.

Resolve old node-gyp errors with @rails/webpacker upgrade

---

app/helpers/allinson_flex/allinson_flex_modified_helper.rb
app/helpers/hyrax_helper.rb
app/views/shared/_select_work_type_modal.html.erb

An issue I sometimes have locally is that I'll try to create a work using an AdminSet that lacks an active_workflow (or a PermissionTemplate on which to hang an active_workflow), and get a Ruby error after submission.
This moves that check into the UI, before selecting an AdminSet.  It also changes the select population to use Solr instead of ActiveFedora for looking up AdminSet titles.

Catch unusable admin sets before work creation

---

app/models/collection_branding_info.rb
config/essi_config.docker.yml
config/essi_config.example.yml

Note that this applies a configuration change, and that updating each existing CollectionBrandingInfo record will be required to apply this change retroactively.

[ESSI-1586] Increase collection banner size

---

app/models/archival_material.rb
app/models/bib_record.rb
app/models/concerns/essi/dynamic_metadata_behavior.rb
app/models/image.rb
app/models/paged_resource.rb
app/models/scientific.rb
app/services/allinson_flex/dynamic_schema_service.rb

For `based_near`:
* restores normal hyrax indexing behavior
* injects `class_name: Hyrax::ControlledVocabularies::Location` into properties for the property
Without these, configuring a `based_near` property in allinson_flex breaks indexing of a work persisting any values to the attribute, raising a ruby error

[ESSI-1598] Restore hyrax based_near behavior allinson_flex overrides

---

app/models/concerns/essi/collection_behavior.rb

Constraining the id argument was a kludge workaround for the rsolr query length limit, and it turns out my constraint was too generous because the query was still too long if you added any other arguments to it.  Changing to a POST call is a proper fix, which will also get us the complete and accurate count.  (There's some eventual limit we could still hit, but some light testing in console suggests we're at least an order of magnitude away from it.)

[ESSI-1595] use POST in collection descendant counts

---

app/helpers/allinson_flex/allinson_flex_modified_helper.rb

The list of adminsets in the new work dialog was using the default solr row limit of 10. This increases it to 1000. I hope we never need that many.

Essi-1602 Specify row limit for AdminSet solr query

---

app/models/concerns/essi/collection_behavior.rb
lib/extensions/hyrax/forms/collection_form/all_files_with_access.rb
spec/models/collection_spec.rb

Sets a default thumbnail, if none is currently set and a default value is available, after a Collection _update_.  (Lookup is not possible until the Collection has been persisted.)

[ESSI-1570] collection save sets default thumbnail

---

lib/extensions/extensions.rb
lib/extensions/hyrax/presenter_factory/solr_row_limit.rb
spec/presenters/hyrax/presenter_factory_spec.rb

I noticed a paged resource with 1111 pages only rendered 1000 pages in UV. This fixes that by raising the limit hard coded in Hyrax::PresenterFactory. Tested with an adapted version of the hyrax presenter_factory_spec.rb

Essi-1604 Increase presenters' solr row limit

---

app/presenters/hyrax/displays_image.rb

Generation of manifests is significantly slowed down by making a fedora request for every fileset. Removing this check might allow a manifest to include a missing image if the fileset has disappeared from fedora for some reason, but otherwise should not have any detrimental effect.
Increased visibility of such a problem might even be benefical?

Essi-1610 Eliminate fedora request during manifest generation

---

config/uv/uv_config.json

This should increase the IIIF server's cache hit rate.

Essi-1611 Adjust size of UV thumbnails to match file manager thumbnails

---

app/models/bulkrax/mets_xml_entry.rb
app/models/mets_document.rb
app/views/bulkrax/importers/_mets_xml_fields.html.erb
lib/iu_metadata/mets_record.rb
spec/iu_metadata/mets_record_spec.rb

* adds `label`, `id` methods to `MetsDocument`
* adds `title` method to `MetsRecord`
* adds `override_title` option to `MetsXmlEntry`, corresponding form

[ESSI-1453] Source and optionally override title in METS import

---

app/search_builders/essi/tree_collection_member_search_builder.rb

The previously merged PR #424 ensured recursive searching through the subcollection tree and to also make sure the same fields were being searched as those in the default global search.  But, it failed to consider that it's the FileSets that actually contain the searchable text from OCR extraction, and it only searched for works.
This PR adds to the search processing chain by calling a method in a Hyrax search builder that finds and joins matching child FileSet IDs.  To do so, it also changes which search builder to inherit from instead of the default Blacklight builder.

ESSI-1578 Adds Solr logic to collection search to find FileSets with matches in full text

---

app/jobs/create_ocr_job.rb
app/views/hyrax/file_sets/_show_details.html.erb
config/routes.rb
lib/extensions/extensions.rb
lib/extensions/hyrax/file_sets_controller/regenerate_ocr.rb

* adds a new job to call `create_ocr_derivatives` instead of `create_derivatives` on the FileSet
* currently, all `create_derivatives` does is call `create_ocr_derivatives`, but relying on that seemed brittle
* adds a new `regenerate_ocr` controller action to call the job
* adds a link to the action
* for some reason the path helper method doesn't exist, so I kludged around it :/

[ESSI-1482] Add action to (re)generate extracted_text OCR

---

app/parsers/bulkrax/mets_xml_parser.rb

Prior file selection logic was grabbing _every_ previously-imported XML file along with the current one.
This fixes that by copying the correct logic over from the current bulkrax `XmlParser`.

[ESSI-1545] Fix bulkrax import post-unzip file selection

---

app/controllers/concerns/essi/ocr_search.rb
app/views/hyrax/collections/_show_document_list_row.html.erb

When searching in collections for matching works, the query term isn't passed in to the detail view to activate the Universal Viewer search.  This overrides the appropriate views to add the query term to the request parameters and changes the method in OCRSearch that sets the highlight parameter so that it comes from the item request params instead of reaching back to the referrer (i.e. the original catalog search URL.)

ESSI 1578 Passes query terms to UV from collection search context

---

app/models/mets_document.rb
lib/iu_metadata/mets_record.rb
spec/fixtures/iu_metadata/pudl0001-4609321-s42.mets
spec/iu_metadata/mets_record_spec.rb
spec/models/bulkrax/mets_xml_entry_spec.rb

Handling the XPATH for `series`, which incorporates a couple of additional namespaces, revealed a couple of things worth noting about handling of namespaces in `nokogiri`:
* by default, nokogiri only acknowledges namespaces declared in the root node
* however, you can aggregate namespaces declared elsewhere with the `collect_namespaces` method
* additional namespaces definitions can be passed in as a second, Hash, argument to the `xpath` method on an XML node
Not sure how we missed the title match failing back in ESSI-1453, but resolved it here.

[ESSI-1617] add more properties to bulkrax mets ingest

---

Gemfile
app/controllers/application_controller.rb
config/essi_config.docker.yml
config/essi_config.example.yml
config/initializers/rack_profiler.rb

Adds a configuration option to control activation of rack_mini_profiler. It is disabled when the config is omitted, but should be enabled on the devel (and possibly staging?) servers.

Essi-1636 Control rack_mini_profiler gem activation from config

---

app/views/records/edit_fields/_description.html.erb

Property-specific view partials are used when available, instead of the default partial (which accounts for allinson_flex dynamic label and hint values).  Hyrax provides partials for some basic/core metadata, including "description", which prevents allinsonflex configuration for label, hint values taking effect.  The applied fix is to override the property-specific partial with a copy of the default partial.
The current list of hyrax-provided edit partials is available here:
https://github.com/samvera/hyrax/tree/v2.9.6/app/views/records/edit_fields
and the up-to-date list for the newest version of hyrax is always available here:
https://github.com/samvera/hyrax/tree/main/app/views/records/edit_fields
To review this change, you will need to have a "description" property configured via your …

[ESSI-1616] "description" display configurable via allinson_flex

---

config/routes.rb

When called by an unathenticated user, bookmarks actions create one-off guest accounts in the database, that then stick around forever.  This change blocks those routes.

[ESSI-1556] Block blacklight bookmark actions that create persistent guest accounts

---

app/controllers/purl_controller.rb
spec/controllers/purl_controller_spec.rb

The default regex in the PURL resolver is tailored to match typical VA# schemes and is too opinionated in the breakdown of expected characters, so it fails to match older P# conventions like Cushman.  This increases the scope with a more inclusive regex, but it still expects a reasonable number of both prefix and serial digits.

Increasing the scope of matching IDs in PURL resolver to work with legacy schemes

---

app/controllers/concerns/essi/works_controller_behavior.rb
app/services/allinson_flex/dynamic_schema_service.rb
lib/extensions/allinson_flex/prepend_work_dynamic_schema.rb

There's a time window after a new AllinsonFlex profile has been saved where trying to render #new for a work generates a Ruby error.  This occurs when #load_allinson_flex in DynamicMetadataBehavior assumes dynamic_schema has returned a non-nil value, when that's the condition we're hitting.
The fix applied here:
* Adds a NoAllinsonFlexSchemaError case to parallel the NoAllinsonFlexContextError case
* in work models, catches and logs the errors
* in work controllers, catches and redirects the errors

[ESSI-1614] catch errors rendering #new with a new AllinsonFlex profile

---

app/models/bulkrax/mets_xml_entry.rb
lib/extensions/bulkrax/csv_entry/add_work_type.rb
lib/extensions/bulkrax/entry/allinson_flex_fields.rb
lib/extensions/extensions.rb

Awhile back, #279 attempted to address the issue of bulkrax import not having loaded flexible metadata properties, but ESSI-1646 captures the finding that this fix only works _sometimes_.  This should be a more robust fix.
There's a little bit of a chicken-and-egg problem here:
* we need to know the imported work's class, in order to call `factory_class.new` and load the most recent allinsonflex profile
* the imported work's class is stored in `parsed_metadata` during `build_metadata`
* `build_metadata` filters which properties are stored in `parsed_metadata` based on what it believes the work class can receive...
* ...which is determined by calling `factory_class`
So, we need to call `factory_class` first in order to get`build_metadata` to build all the flexible metadata, but we need to …

[ESSI-1646] improve flexible metadata reliability in bulkrax import

---

config/essi_config.docker.yml
config/essi_config.example.yml
public/404.html

The current default behavior of the PURL resolver when it fails to find a match is to redirect out to the old Variations access CGI.  This behavior came from Pages Online, which was predominantly musical scores.  What we want now is to redirect to the global 404 response within the application.  
We already had the ability to configure the rescue URL in the application configuration YAML, so this just changes the default to be a generic works endpoint that should always force the 404 response, like:
https://localhost:3000/concern/works/missingWorkID
Note the "configuration change" label as a reminder to set the value on deployed instances.  This path can be taken from the example config (`/concern/works/%s`), but could be anything that will be handled internally as a 404, like:
/404 …

Essi 1488 purl 404

---

app/models/bulkrax/mets_xml_entry.rb
app/presenters/hyrax/select_collection_list_presenter.rb
app/views/bulkrax/importers/_mets_xml_fields.html.erb
spec/presenters/hyrax/select_collection_list_presenter.rb

Adds optional selection of a Collection to use for METS ingest.
Note that unlike CSV ingest, which looks up a collection by title/source value and will create a collection if a match is not found, this only finds an existing collection that the user has deposit rights to.  See wiki page "Bulkrax: collection import and association" for more details.

[ESSI-1645] import collection field (via bulkrax METS import)

---

Gemfile
Gemfile.lock
config/application.rb

Addresses CVE-2022-32224
Removes some debugging gems from the Gemfile that Rubymine installs custom versions of.

Essi-1657 Update to Rails 5.2.8.1 and remove debase, ruby-debug-ide gems

---

docker-compose.yml

Solves issues with git sourced gem availability in docker-compose.
Also reduce sidekiq threads to match deployed configurations.

`bundle install` before starting docker services

---

Gemfile
Gemfile.lock
spec/features/csv_importer_spec.rb
spec/rails_helper.rb

The theory on the csv import spec non-deterministically failing is that it's hitting a race condition on the closing the modal and the updating of the rest of the page.
This attempts to address that by adding the CapybaraWatcher gem, and adding a wait call around checking for "Cloud Files Added"

[ESSI-1665] add CapybaraWatcher gem; add wait call in csv import spec

---

config/essi_config.docker.yml
config/essi_config.example.yml
config/initializers/airbrake.rb

When configured this should allow the ESS hosted applications to access Airbrake's servers.

ESSI-1675 Add config to support airbrake proxy use

---

app/presenters/hyrax/select_collection_list_presenter.rb

This is functionally equivalent to the previous version of the method, but stays safely below the solr query header size limit that we started exceeding once we had around 159 collection ids.

[ESSI-1684] slice collection ids to restrict solr query header size

---

lib/extensions/bulkrax/csv_entry/add_work_type.rb

CSV import is dependent upon having "model" positioned in the first column, in order to assign the correct `factory_class` and accurately determine `field_supported?` results appropriate for the specified import class (instead of just assuming the default class of `Image`) while parsing the remaining columns.
This PR monkeypatches the `build_metadata` logic to robustly handle the "model" value being in any column.

[ESSI-1690] bugfix for missing csv import fields

---

app/authorities/qa/authorities/iucat_libraries.rb
config/authorities/holding_locations.yml
config/authorities/supplemental_holding_locations.yml
lib/extensions/active_fedora/file/escaping_obsoletions.rb
lib/extensions/hydra/access_controls/permission/escaping_obsoletions.rb
spec/authorities/qa/authorities/iucat_libraries_spec.rb
spec/fixtures/vcr_cassettes/iucat_libraries_up.yml

Adds a local YAML file to inject additional holding location into API results.  In the event both sources provide a holding location, the API's data is used.
Also includes a tweak to correctly handle API lookup of code values that contain spaces.  Note that this is done by `Addressable::URI.escape` rather than `CGI.escape` -- turns out the latter method encodes spaces as "+" instead of "%20" as `URI.escape` (deprecated) does.  3rd commit applies this fix in 2 other places, as well.

[ESSI-1667] additional holding locations

---

app/assets/images/blacklight/repository.svg
app/assets/stylesheets/brand_tweaks.css
app/models/solr_document.rb
app/renderers/campus_attribute_renderer.rb
app/renderers/campus_collection_breadcrumb_renderer.rb
app/services/essi/adapters/nesting_index_adapter.rb
app/views/catalog/_index_list_default.html.erb
app/views/catalog/_thumbnail_list_collection.html.erb
config/initializers/samvera-nesting_indexer_initializer.rb
spec/renderers/campus_attribute_renderer_spec.rb

The first couple of commits copy and modify hyrax's `NestingIndexAdapter` to add an additional property.
* It would probably be more elegant to monkeypatch the hyrax version, but I ran into repeated problems doing that, and reverted to a strict override
* Note that here's active work on deprecating `NestingIndexAdapter` in future versions of hyrax
* At some future point, we can slim down the essi version to just the portion we're still using, or otherwise refactor
* Note that works and collections will need to be re-saved to update their solr indices, to provide values for the UI components
3rd commit adds UI components to render the breadcrumbs
The next couple of commits copy and modify a hyrax partial -- there are distinct partials to display collection thumbnail and work thumbnails, …

[ESSI-1622] add campus collection breadcrumbs to catalog results

---

app/renderers/campus_attribute_renderer.rb
lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb
spec/renderers/campus_attribute_renderer_spec.rb

Adds allinson_flex metadata fields in the IIIF manifest.
Adds handling of campus as another specially-rendered field (along with holding_location), and fixes display on the work show page to use the campus label (rather than internal code value).

[ESSI-1692] dynamic manifest metadata

---

config/initializers/okcomputer.rb
lib/essi_dev_ops/image_sync_check.rb

Since Sidekiq is likely to run in a separate container, possibly on a separate server, it is important to have some way of making sure that it is running the same commit level as the web container.  This adds a check to OK Computer that compares commit levels from image data extracted during the deployment process.  
It is a bit opinionated in that it assumes the existence of certain files created by running `podman image inspect` on the web and job  images.  Those files are visible from either container due to their location in the shared secrets directory, which allows this status check to open them and compare the environment variable SOURCE_COMMIT.
The status check is only registered if it detects a certain flag file in the secrets directory.  This allows easily configuring this check …

ESSI-1698 Adds okcomputer check to compare image commit levels

---

Dockerfile
config/ImageMagick-6/policy.xml

Large files were failing during derivative creation due to MiniMagick hitting memory limits. The default ImageMagick policies for resources in the base image are too restrictive, so this PR overwrites the policy definitions (in `config/ImageMagick-6/policy.xml`  with a stashed version that increases resource values for memory and dimensions. 
You don't need to ingest a large file to see if this works in the resulting image build.  Get a shell in the container and use  `convert` to list the resource limits.  It should produce the following, which is known to work both locally and on the server:
```
$ convert -list resource
Resource limits:
Width: 32KP
Height: 32KP
List length: unlimited
Area: 128MP
Memory: 5GiB
Map: 1GiB
Disk: 5GiB
File: 12288
Thread: 4
Throttle: 0
Time: unlimited
```

ESSI-1724 Overriding ImageMagick policy.xml to fix large file failures

---

app/actors/hyrax/actors/file_actor.rb
app/jobs/characterize_job.rb
spec/actors/hyrax/actors/file_actor_spec.rb

File ingest, in the case of both `store_files?` and `transform_to_jp2?` being true, was leaving a .jp2 file around indefinitely post-ingest, in the pattern of:
`/tmp/{tmpdir}/{original file}.jp2`
e.g.
`/tmp/d20221230-1-zz7hny/VAB8235-U-00446-00002.jp2`
This commit adds an argument to trigger cleanup at the end of `CharacterizeJob`, when the .jp2 is no longer needed.  (The `CreateDerivativesJob` called next uses the original .tiff file.)

[ESSI-1765] have CharacterizeJob optionally unlink characterization file, parent dir

---

.circleci/config.yml

Also updates the browser-tools orb, but this is likely not the cause of the git checkout error. Reports are the chrome license file was being left behind.

Move circleci checkout above browser-tools install

---

Gemfile.lock

To resolve airbrake dashboard warning about "outdated notifier library."

update airbrake-ruby gem

---

lib/extensions/extensions.rb
lib/extensions/hyrax/file_set_presenter/viewing_hint.rb
lib/extensions/iiif_manifest/manifest_builder/canvas_builder/viewing_hint.rb
lib/extensions/iiif_manifest/manifest_builder/image_builder/viewing_hint.rb

The ESSI-588 monkeypatch to add page-level viewingHint values in the manifest was:
1.  ineffective, due to inclusion via `include` instead of `prepend`
2. inefficient, due to running a solr query to look up the `FileSet` `viewing_hint` property, when that's available from the already-built `FileSetPresenter` that `CanvasBuilder` has access to when calling `image_builder`
This PR should resolve both issues.
Note that the current UV does not seem to actually file-specific viewing_hint properties; presumably a future version may.

[ESSI-588] refactor manifest viewing hint

---

app/actors/hyrax/actors/file_actor.rb
lib/extensions/attach_files_to_work_with_ordered_members_job/import_metadata.rb
lib/extensions/bulkrax/csv_entry/add_file_metadata.rb
lib/extensions/bulkrax/object_factory/file_factory_metadata.rb
lib/extensions/extensions.rb
lib/extensions/hyrax/actors/create_with_files_actor/uploaded_files.rb
lib/extensions/hyrax/actors/create_with_files_ordered_members_actor/attach_files_with_metadata.rb
lib/extensions/hyrax/uploaded_file/uploaded_file_metadata.rb
spec/actors/hyrax/actors/file_actor_spec.rb

In bulkrax CSV import, the `file` column provides a list of filenames to ingest.  This adds a `file_label` column to optionally provide file label values, and discontinues the `transform_to_jp2` method overwriting the file label value (substituting .jp2 for .tif+).
~~A test is currently failing that _looks_ like it would be pertinent, but it's coincidentally one that sometimes fails non-deterministically, so I'm re-running it and hoping it will pass in CircleCI like it does locally.~~ Test is passing after a retry :)

[ESSI-875] bulkrax csv import of page labels

---

app/renderers/holding_location_attribute_renderer.rb

Rendering code assumes both email and telephone are provided.  This revision should properly handle either/neither/both values being present.

[ESSI-1786] holding location rendering: handle missing contact values

---

spec/support/shared_examples/paged_structured_controller.rb

This is a temporary solution to making CI work.  IIIF Print currently does not support structures, so we need to skip the specs that test that functionality for now.  When structures are supported in the near future, we can remove/modify the specs in the new paradigm.
After this ticket is solved, we can reworked these specs https://github.com/scientist-softserv/essi/issues/13

Make specs pass

---

.github/workflows/dockerimage.yml
.github/workflows/dockerimage_stable.yml
.github/workflows/dockerimage_test.yml
Dockerfile
Gemfile.lock
config/essi_config.docker.yml
config/fedora.yml
config/initializers/iiif_print.rb
config/initializers/sidekiq.rb
docker-compose.yml
lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb
spec/support/capybara.rb

ref: https://github.com/scientist-softserv/essi/issues/20
This commit updates the #manifest_metadata to use the IIIF Print implementation.  We add a configuration to account for the additional metadata that is found in `ESSI.config[:essi][:metadata][:iiif]`.

[i20]-Use IIIF Print's manifest metadata

---

app/jobs/reindex_collections_job.rb
app/jobs/reindex_file_sets_job.rb
app/jobs/reindex_works_job.rb

A starting point for jobs that can reindex works, file_sets, or collections independently.  
Note that the `update_index` method for Collection triggers the nested indexer, which we want to find a way around before using for large amounts of data.

Adding jobs to provide finer control over batch index operations

---

.circleci/config.yml

Fixes CircleCI build
Webpack 4 is incompatible with the new OpenSSL support in Node 18. We're likely stuck on webpack 4 as it's a direct dependency of rails webpacker.

Use legacy openssl option for node 18 & webpack 4

---

app/helpers/prederivation_helper.rb
app/services/essi/file_set_ocr_derivatives_service.rb
app/services/processors/ocr.rb
config/essi_config.docker.yml
config/essi_config.example.yml
lib/extensions/extensions.rb
lib/extensions/hydra/works/characterization_service/precharacterization.rb
spec/services/hyrax/derivative_service_spec.rb

Follows the same pattern we have for using pre-derived OCR:
1. Look for a pre-derived file, in the configured directory, with a filename matching the original but substituting "-characterization.xml" for the original file suffix
2. If found, use that file; if not, revert to original behavior (generating characterization via the hyrax stack)
Third commit:
1. refactors into a module, code that was common across the two pre-derivation cases (file characterization, OCR)
2. allows for both IUPUI and IUB style of specifying a derivation folder -- a single folder for everything, vs nested work_id/type subfolders
Fourth commit changes the `skip_derivatives` setting from (when true) doing a "hard skip" of OCR (neither generating it, nor reading pre-provided) to a "soft skip" (using pre-derived …

[ESSI-1805] [ESSI-1812] ingest prederived characterization

---

Gemfile.lock
app/jobs/characterize_job.rb
app/jobs/concerns/sequential_job.rb
config/initializers/sidekiq.rb
docker-compose.yml

Update to Sidekiq 7 which required refactoring of our configuration.
CharacterizationJob is sent to the 'derivatives' queue, and CreateDerivativesJob follows suit.
A dedicated sidekiq worker process is setup to allow parallel processing.

Essi-1809 derivatives/imageproc queue; Sidekiq 7

---

app/actors/hyrax/actors/ordered_members_actor.rb
app/jobs/clean_list_source_job.rb

This should fix the problem of list_source accumulating old resources when adding a new file to a work (or until recently, just saving the work without adding files).
~~Still need to find a way to identify and cleanup our existing bloated list_source data...~~
Now includes a clean up job.

Essi-1815 list source bloat

---

config/locales/blacklight.en.yml

The flexible metadata label is being ignored because [the hyrax attribute render preferentially uses blacklight-configured values, if provided](https://github.com/samvera/hyrax/blob/v2.9.6/app/renderers/hyrax/renderers/attribute_renderer.rb#L50-L60) and [we're inheriting such values from hyrax](https://github.com/samvera/hyrax/blob/v2.9.6/config/locales/hyrax.en.yml#L16-L28).
This resolves the issue by nullifying the hyrax-inherited value.  Possibly alternative approaches include rewriting `#label` to give preference to flexible metadata label values over hardcoded blacklight locale config values.  Also note that we should expect to find the same behavior with the other properties given search.fields.show values:
* admin_set
* based_near_label
* keyword

[ESSI-1822] remove hyrax-inherited display label for contributor

---

lib/extensions/allinson_flex_extensions.rb

Create transient new objects for all registered work types. Attempts to work around failures to define methods for some properties when loading works (e.g. missing ocr_state)

ESSI-1837 Load all work classes at startup

---

lib/extensions/extensions.rb
lib/extensions/hydra/derivatives/processors/wait_readable.rb

Patch Jpeg2k ShellBasedProcessor to handle IO::WaitReadable errors
This patches a method from ShellBasedProcessor but Processors::Jpeg2kImage is what the patch needs
to be applied to because it includes ShellBasedProcessor.
Can be removed when we start using hydra-derivatives 3.8

Essi-1838 Handle IO::WaitReadable errors

---

lib/extensions/allinson_flex_extensions.rb
spec/rails_helper.rb

In draft status pending a rewrite, to an approach that works across all of local, docker, circleCI, and production.
I'm coming across two issues:
**1) AdminSet**
We ensure the existence of the default AdminSet at the start of each test suite:
https://github.com/IU-Libraries-Joint-Development/essi/blob/v1.4.8/spec/rails_helper.rb#L85-L88
but now that we also load allinson_flex classes during server initialization:
https://github.com/IU-Libraries-Joint-Development/essi/blob/v1.4.8/lib/extensions/allinson_flex_extensions.rb#L33-L38
and that happens, first, I'm finding that specs choke during the allinson_flex initialization, here:
https://github.com/IU-Libraries-Joint-Development/essi/blob/v1.4.8/app/services/allinson_flex/dynamic_schema_service.rb#L141
since the default admin set hasn't …

load default AdminSet prior to allinson_flex initialization

---

config/database.yml
spec/features/log_in_as_spec.rb

This PR gets the `log_in_as` specs passing, which started consistently failing after measures were put in place to ensure proper creation of default admin set/permission templates. It was failing while waiting for a lock on the `User` table:
```
ActiveRecord::LockWaitTimeout:
Mysql2::Error::TimeoutError: Lock wait timeout exceeded; try restarting transaction: INSERT INTO `users` (`email`, `created_at`, `updated_at`, `provider`, `uid`) VALUES ('user130@example.com', '2023-08-11 19:54:15', '2023-08-11 19:54:15', 'cas', 'username130')
```
I wasn't able to determine what was really holding the database lock, but I was able to get past it by increasing the INNODB lock timeout in the test database configuration.  This has resulted in at least a 50 second wait in the suite, which you can see at …

Test initialization refactor

---

app/controllers/purl_controller.rb
spec/controllers/purl_controller_spec.rb

The functionality to set the active page in the UV, upon resolving a PURL and entering a work, was accomplished by parsing IDs on dashes and assuming that the extra values were appended as the desired volume/page, like:
VAX1234-1-0003 = Page 3 of volume 1
But this hijacks valid IDs like:
VAX1234-U-00003
It was decided that we should disable this behavior for now and implement something more RESTful that follows IIIF nomenclature to specify a target canvas (page.)

ESSI-1849 Disable parsing of IDs on dashes in PURL controller to set active page in UV

---

app/models/solr_document.rb
app/presenters/concerns/essi/presents_delegated_attributes.rb

For local testing, you can override the cache settings login in config/environments/development:20-31 by appending `config.cache_store = :file_store, "#{Rails.root}/tmp/cache"` and then watching the contents of that directory.

[ESSI-1847] provide presenter #version method for manifest caching

---

app/controllers/catalog_controller.rb
app/indexers/essi/file_set_indexer.rb
app/indexers/indexer_helper.rb
app/jobs/reindex_collections_job.rb
app/jobs/reindex_file_sets_job.rb
app/jobs/reindex_works_job.rb
app/models/concerns/essi/ocr_behavior.rb
app/models/solr_document.rb
config/essi_config.docker.yml
config/essi_config.example.yml
config/initializers/iiif_print.rb
config/initializers/samvera-nesting_indexer_initializer.rb

When reindexing all works and collections, we want to control the depth of the nested indexer to just the level of the objects being acted upon. The depth of the nested indexer is set in an initializer, which was hardcoded at 5 but is now configurable in secrets as `essi, :nested_indexer_depth` .  
NOTE that anytime this is set lower than 3 to 5, it is nearly guaranteed that the depth limit will be exceeded and will raise an exception, so it must be handled properly if the goal is to merely skip child indexing.  See the modified batch indexers also in this PR.  Lowering the limit should be done deliberately when the indexing code or caller is aware of the limit.
The re-indexing jobs for works, FileSets, and Collections query Solr for documents that have yet to be updated for the purposes …

Improvements to indexing jobs to handle large scale reindexing operations

---

app/views/catalog/_index_gallery.html.erb
app/views/catalog/_index_gallery_collection_wrapper.html.erb
app/views/catalog/_thumbnail_list_collection.html.erb
app/views/hyrax/base/_member.html.erb
app/views/hyrax/collections/_collection_row.html.erb
app/views/hyrax/collections/_show_document_list_row.html.erb
app/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb
app/views/hyrax/dashboard/collections/_subcollection_row.html.erb

Displays the object title or label as the alt text when rendering thumbnail links.
Should fix essi-1895 and essi-1898

Essi-1860 thumbnail alt text

---

app/views/hyrax/base/_representative_media.html.erb

The en i18n string is "No preview available"

ESSI-1894 Provide alt text for default image

---

app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
app/views/layouts/boilerplate.html.erb
config/uv/uv.html

This should resolve 4 remediation issues (essi-1904 essi-1905 essi-1906 essi-1907).
I noticed our `app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb` file is now sourced from the iiif-print gem.
I did not perceive any difference in the zoom behavior of UV after setting `user-scalable=yes`

Essi-1860 UV a11y remediation

---

app/indexers/essi/file_set_indexer.rb
app/jobs/reindex_collections_job.rb
app/jobs/reindex_file_sets_job.rb
app/jobs/reindex_works_job.rb

Based on trial and error, this PR adds more ability and refinements to the reindexing jobs.  It adds more ability to track status and failures in versioned log files, and allows constraining single invocations to a particular work type (useful for parallel processing because it avoids two threads trying to work on the same set of IDs obtained through the Solr queries.)
Also, it was found through testing that FileSets were taking a long time to index due to duplicate LDP load operations in the FileSetIndexer.  Those were being caused by repetitious calls to the FileSet's parent when storing membership details in Solr fields.  This refactors to only access the parent once, which takes the average time from 9 seconds to 3.

More improvements to reindexing jobs

---

app/controllers/catalog_controller.rb
app/models/iiif_search_builder.rb
config/database.yml
lib/extensions/extensions.rb
lib/extensions/iiif_print/blacklight_iiif_search/annotation_decorator/annotation_decorator_compatibility.rb
lib/extensions/iiif_print/iiif_search_decorator/search_decorator_compatibility.rb

Overriding certain decorator methods to make previous FileSet index state compatible with iiif_print until they are reindexed.

Workarounds to make previous IIIF search fields compatible with iiif_print

---

app/helpers/prederivation_helper.rb
app/services/processors/ocr.rb
spec/services/hyrax/derivative_service_spec.rb

It looks like the #encode_file action presumes #encode output something:
https://github.com/samvera/hydra-derivatives/blob/v3.6.1/lib/hydra/derivatives/processors/shell_based_processor.rb#L30-L35
But, it's possible that it didn't, in the case where we've got "skip_derivatives: true" and no pre-derived OCR was provided.
This changes #encode_file to only try to attach the file output by #encode, if that file actually exists.

Handle skipping OCR

---

app/views/hyrax/base/_member.html.erb

In a context of nested membership across model types, the #title_or_label method can produce a ruby error, because it's defined (well, delegated to the solr_document) for Collection and FileSet presenters, but not the work presenter.  This replaces the call with #to_s, which is provided by all the presenters, and which itself just delegates to the solr document's #title_or_label, anyway.
An alternative solution would be to add :title_or_label to the methods that the work show presenters delegate to the solr_document.  But this felt cleaner.
Failing spec is unrelated and resolved by #587

tweak member partial with more reliably present #to_s

---

spec/controllers/hyrax/dashboard/collections_controller_spec.rb
spec/models/collection_spec.rb

It looks like we're _sometimes_ getting [the "Persisted collection" from the Collection model spec](https://github.com/IU-Libraries-Joint-Development/essi/blob/v1.4.12/spec/models/collection_spec.rb#L6) or the ["Test collection" from the Collection controller spec](https://github.com/IU-Libraries-Joint-Development/essi/blob/v1.4.12/spec/controllers/hyrax/dashboard/collections_controller_spec.rb#L8) persisting afterwards, into the Collection authority spec, and [creating a test failure](https://app.circleci.com/pipelines/github/IU-Libraries-Joint-Development/essi/2452/workflows/e3270262-8b6e-4cc8-88d4-bedc37696827/jobs/2706).
This attempts to resolve that by changing direct `Collection #create, #new` calls to `FactoryBot #create, #build`.  (But I am kinda surprised the `:clean` settings in …

reassign spec Collection create/build to FactoryBot

---

lib/extensions/extensions.rb
lib/extensions/hyrax/work_show_presenter/member_presenter_factory_memoization.rb
lib/extensions/iiif_manifest/manifest_builder/deep_file_set_enumerator/nested_each.rb

It turns out that [IIIFManifest::ManifestBuilder::DeepCanvasBuilderFactory#file_set_presenters](https://github.com/samvera/iiif_manifest/blob/v0.5.0/lib/iiif_manifest/manifest_builder/deep_canvas_builder_factory.rb#L7) calls a DeepFileSetEnumerator that [explicitly lists all direct member FileSets, _then_ loops through member works](https://github.com/samvera/iiif_manifest/blob/v0.5.0/lib/iiif_manifest/manifest_builder/deep_canvas_builder_factory.rb#L18-L25).  So, that explains why we're seeing exactly that behavior.
These commits provide a proof-of-concept change to produce the expected and desired behavior of FileSet descendants getting listed in the manifest sequentially, regardless of their depth in the tree. 
Unrelated failing test is resolved via #587 
Needs view partial fix …

[ESSI-1879] nested filesets in iiif manifests

---

app/controllers/robots_controller.rb
app/views/hyrax/dashboard/sidebar/_configuration.html.erb
app/views/robots/_form.html.erb
app/views/robots/edit.html.erb
config/routes.rb
public/robots.txt
spec/controllers/robots_controller_spec.rb

Adds the ability to change the content of robots.txt without redeployment or restart.
Editor access is provided to admins in the settings section of the dashboard.

Essi-1925 Do the Robot 🤖

---

spec/authorities/qa/authorities/collections_spec.rb

Another attempt to avoid that flaky test failure

replace #contains_exactly with #contains check to kludge around spec Collection persistence

---

app/actors/essi/actors/create_with_remote_files_ordered_members_structure_actor.rb
lib/extensions/bulkrax/object_factory/create_with_dynamic_schema.rb
lib/extensions/extensions.rb
lib/extensions/hyrax/actors/file_set_actor/create_content.rb
lib/extensions/iiif_print/data/inherit_permissions_job_calls.rb

Currently, there are duplicate job calls made to:
* `InheritPermissionsJob`
* `VisibilityCopyJob`
across multiple places:
* `CreateWithRemoteFilesOrderedMembersStructureActor#create` (but not `#update`) 
* `IiifPrint::Data.handle_after_create_fileset` (applied to the `:after_create_fileset` callback)
* `FileSetActor#create_content`, specifically in the `from_url` branch case
The latter two call contexts produce, not only redundancy, but exponentially poor performance.  The jobs are called from each `FileSet`, but then run on the work, and loop through _all_ child FileSets.
The set of changes applied here:
* Adds coverage in the `#update` case, alongside the existing `#create` case, in the work-level context
* Removes the jobs calls from the latter two, FileSet-specific, contexts
* adds a …

[ESSI-1932] consolidate FileSet Inherit, Copy job calls into work actor 

---

app/views/_masthead.html.erb
app/views/shared/_collection_banner_link.html.erb
app/views/shared/_collection_title_link.html.erb
lib/extensions/hyrax/file_set_presenter/collection_banner.rb
lib/extensions/hyrax/work_show_presenter/collection_banner.rb
spec/presenters/hyrax/file_set_presenter_spec.rb
spec/presenters/hyrax/work_show_presenter_spec.rb

Two performance issues addressed here, in the FIleSetPresenter and WorkShowPresenter logic for collection lookup:
* both currently  make Fedora lookups to build a collection presenter, where a solr lookup suffices and is more performant
* a lack of memoization leads to the WorkShowPresenter collection lookup getting called twice, where once should suffice.

[ESSI-1947] refactor banner lookup fedora query to solr query, add memoization

---

app/assets/stylesheets/digital_collections/_layout.scss
app/views/hyrax/homepage/_featured_fields.html.erb
app/views/hyrax/homepage/_featured_works.html.erb
app/views/hyrax/homepage/_home_content.html.erb
app/views/hyrax/homepage/_recent_document.html.erb
app/views/hyrax/homepage/_recently_uploaded.html.erb

This PR will make a noticeable change to the home page.
1. Moves "View All Collections" Button up to just below Campus Collection options.
2. Removes Featured Works and Recently Uploaded buttons
3. Displays Featured Works - if any - as left column on large screens
4. Displays Recently Uploaded as right column on large screens if Featured Works
5. Both sections expand to full width on medium screens and smaller 
6. Adds alt text to works thumbnails in both sections
Resolves SiteImprove Issues:
- Role with implied hidden content has keyboard focus
- Image missing a text alternative

[ESSI-1928] Hidden content focusable

---

config/uv/uv.html

According to [MDN Webdocs](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag), viewport maximum-scale should be set to 3 or higher for accessibility reasons.

[ESSI-1927] Accessibility fix. Sets UV maximum-scale to 3.

---

lib/extensions/extensions.rb
lib/extensions/hyrax/actors/apply_order_actor/add_members_single_save.rb

Saves once after adding all new ordered_members, rather than once per item.

[ESSI-1949] add members via a single save

---

config/context.yml

Resolves the expected vs actual predicates for two properties that are configured as dc/terms rather than dc/elements, currently blocking successful remote metadata import:
* creator: http://purl.org/dc/elements/1.1/creator vs http://purl.org/dc/terms/creator
* subject: http://purl.org/dc/elements/1.1/subject vs http://purl.org/dc/terms/subject
* date_published (date_created): http://purl.org/dc/terms/issued vs http://purl.org/dc/terms/date

[ESSI-1280] remote metadata lookup

---

app/controllers/concerns/essi/dynamic_catalog_behavior.rb

Blacklight facet behavior is problematic when limit is undefined, or explicitly false or nil.  Our other facets in `app/controllers/catalog_controller.rb` all have `limit: true` (which is functionally equivalent to `limit: 10`), so this change adds that setting for allinson_flex facets.

Display "more >>>" links for facets missing them (limited to first 10)

---

app/views/records/edit_fields/_source_metadata_identifier.html.erb

Adds block of help text regarding how retrieving, refreshing metadata does not apply to Image or Scientific work types

add more hint text for source metadata identifier behavior across worktypes

---

app/helpers/facet_helper.rb
app/views/records/show_fields/_campus.html.erb

For facet display of campus, uses label value (e.g. "IU Indianapolis") for link text, but retains use of code value (e.g. "IUI") for link destination.

[ESSI-2025] campus facet display

---

app/indexers/concerns/essi/indexes_num_pages.rb

We do need the 2nd part of this module to provide the indexing needing to sort by page count, but the first part is both:
- redundant, as allinson_flex can configure indexing and faceting
- brittle, as it can error out on a worktype that does not unconditionally provide the `num_pages` attribute
You can test this locally by removing `num_pages` from a specific worktype -- say, BibRecord -- and try saving an instance of that worktype.  Without this fix, you should get a ruby error; with this fix, it should successfully save.

[ESSI-2021] drop indexing now provided by allinson_flex

---

lib/extensions/extensions.rb
lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb
lib/extensions/iiif_print/iiif_manifest_presenter_behavior/manifest_metadata.rb
lib/extensions/iiif_print/manifest_metadata.rb

`iiif_print` looks up the allinson_flex Profile records directly, which makes it context-unaware.  This results in always using the default label, which can result in an inconsistency with the Show page where context-aware dynamic_schema lookup is used.
This  patches `iiif_print` behavior to be context-aware, until such time as the issue is patched upstream.
_This does not currently recreate [the special handling of the collection property](https://github.com/scientist-softserv/iiif_print/blob/main/lib/iiif_print.rb#L262-L264); we should test whether that needs to be added._
Raised corresponding issue upstream at:
https://github.com/scientist-softserv/iiif_print/issues/378

[ESSI-2027] use context-specific manifest metadata labels

---

app/services/essi/external_storage_service.rb
config/initializers/okcomputer.rb
lib/essi_dev_ops/external_storage_check.rb

Removes any trailing slash from the IIIF server url when configuring that OkComputer check. Our Cantaloupe 5 server is redirecting when it is present and that is not allowed by the check.
Adds a check for the external storage service. This is implemented as a HEAD request for the bucket.

Essi-2033 IIIF and external storage checks

---

app/indexers/essi/file_set_indexer.rb
app/models/collection_branding_info.rb
spec/factories/collection_branding_infos.rb
spec/models/collection_branding_info_spec.rb

Note that during a FileSet's creation, whether in the UI or bulkrax upload, it is initially saved as an orphan, and parent information is added in a subsequent re-save.  (I initially logged a warning when a file was saved in an orphan state, but removed that line as it would provide more noise than signal.)

[ESSI-2023] add FileSet indexing re: parentage, collection branding use

---

.circleci/config.yml
spec/actors/hyrax/actors/file_actor_spec.rb

Adds spec for enabled external storage. We may want to enable external storage for all tests via essi_config.example.yml?

External body spec

---

app/controllers/purl_controller.rb
app/helpers/catalog_helper.rb
app/models/collection_branding_info.rb
app/models/file_set.rb
app/presenters/hyrax/displays_image.rb
app/services/essi/generate_pdf_service.rb
app/services/iiif_collection_thumbnail_path_service.rb
app/services/iiif_file_set_path_service.rb
app/services/iiif_thumbnail_path_service.rb
config/essi_config.example.yml
lib/extensions/extensions.rb
lib/extensions/hyrax/file_set_presenter/content_location.rb
spec/models/collection_branding_info_spec.rb
spec/services/iiif_file_set_path_service_spec.rb

Refactors lookup of IIIF image server URLs (in a manner aware of external_storage settings), and applies that logic where not yet present.
New/modified infrastructure:
* [app/services/iiif_file_set_path_service.rb](https://github.com/IU-Libraries-Joint-Development/essi/pull/648/files#diff-793f5625c32e4b74214afdead845769c64bae3a4bed2a7873646b05b879066f2) (new, replaces direct calls to `Hyrax.config.iiif_image_url_builder`, `Hyrax.config.iiif_info_url_builder`)
* [app/models/file_set.rb](https://github.com/IU-Libraries-Joint-Development/essi/pull/648/files#diff-bac0cfdccf9a69b2827b98b88a6416464fb0313eb425e7be2cfc0a3e04d2b53f) (modified)
* Hyrax::FileSetPresenter [modified via an extension](https://github.com/IU-Libraries-Joint-Development/essi/pull/648/files#diff-b0e14a4db0e2bcfe494d6a4f819e …

[ESSI-2062] fix iiif urls unaware of external_storage

---

lib/extensions/bulkrax/entry/multiple_check.rb
lib/extensions/extensions.rb

Similar in spirit to our existing `SingularizeRightsStatement` patch, just stops a hard assertion that `rights_statement` is _necessarily_ multi-valued, and instead just _checks_ whether it's multi-valued, like it does for every other property that's not specific to bulkrax import (file, remote_files, parents, children).

[ESSI-875] patch Entry#multiple? to stop forcing rights_statement multi-valued

---

app/controllers/concerns/essi/dynamic_catalog_behavior.rb

Speeds up catalog controller responses by applying a similar tactic as in #381 to load the flexible metadata profile during initialization of the catalog controller. We might consider calling this during application init to avoid slow initial requests after restarts.

Essi-2094 Only reconfigure catalog when flex metadata profile is updated.

---

lib/extensions/extensions.rb
lib/extensions/iiif_print/catalog_search_builder/fix_is_child_filtering.rb

Patch for iiif_print issue: https://github.com/notch8/iiif_print/issues/389
Before patch, on current main: after saving a work with an `is_child` value assigned (of `true` or `false`), resulting in some value being indexed in the solr field `is_child_bsi`, the work stops appearing in catalog search results.  It only appears when the `is_child` value in `nil`, resulting in no `is_child_bsi` solr index value.
After patch: work should start showing up in catalog search results, again.
Note that although bug is also present in `IiifPrint::HomepageSearchBuilder`, we're only using `IiifPrint::CatalogSearchBuilder`.

[ESSI-2106] patch works disappearing from search results after bulkrax update

---

app/helpers/prederivation_helper.rb
spec/services/hyrax/derivative_service_spec.rb

The `PrederivationHelper` helper expects files to be grouped into folders whose names are derived from the filenames (i.e. `VAA1234/VAA1234-0001.tif`) .  That's so that root level folders don't accumulate thousands of files that are hard to browse or could become a performance problem.  But, that ends up not working for the case where file naming is random, variable length, and contains no hint of a logical grouping (i.e. `P01234.tif`, `P0000001.tif` etc.)
This PR adds the ability to look for matching derivative files in generic "ungrouped" folders, so that resulting files (i.e. from `imageproc`) can just output to:
```
jp2/ungrouped
ptif/ungrouped
ocr/ungrouped
characterization/ungrouped
```
It still maintains the ability to process files that are logically grouped into folders and the …

Refactoring PrederivationHelper to allow for derivatives not grouped in folders by ID

---

app/models/archival_material.rb
app/models/bib_record.rb
app/models/collection.rb
app/models/concerns/essi/ordered_members_nil_values.rb
app/models/concerns/essi/solr_error_behavior.rb
app/models/file_set.rb
app/models/image.rb
app/models/paged_resource.rb
app/models/scientific.rb

Investigating the broken works for ESSI-2119 ran across a couple of cases where uncaught errors can arise.  The changes here don't catch them, but do add outermost wrappers to log them when they arise:
`#to_solr` has a pretty deep stack of `super` calls, with errors possible at each step.  This adds a new outermost `#to_solr` to log any errors.
`#ordered_members` isn't supposed to ever contain `nil` values, but sometimes it does, which breaks (among other things) `#ordered_works` calls.  This adds a module to log an error for `nil` values, any time they are found during an `#ordered_members` call.

[ESSI-2119] more error logging

---

app/jobs/characterize_job.rb
app/jobs/create_ocr_job.rb
app/models/file_set.rb
app/services/essi/external_storage_service.rb
app/services/essi/generate_pdf_service.rb
lib/extensions/hyrax/downloads_controller/external_storage.rb
spec/models/file_set_spec.rb
spec/services/essi/external_storage_service_spec.rb

Currently, the CharacterizeJob and download action have logic to retrieve files from either Fedora or S3 storage, but corresponding updates are missing from CreateOCRJob and PDF generation.
First commit applies corresponding updates where they're missing; second commit condenses duplicate logic into new methods.

[ESSI-2130] apply Fedora/S3 file retrieval for OCR generation, characterization, PDF generation, download
