app/assets/stylesheets/application.scss, app/assets/stylesheets/brand.css, app/views/layouts/hyrax.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb
Added IU branded header and footer. They are similar as pages.dlib.indiana.edu.
=> ESSI-30 add IU-branded header and footer in the application

spec/actors/hyrax/actors/file_actor_spec.rb, spec/factories/paged_resources.rb, spec/indexers/paged_resource_indexer_spec.rb
Fix broken specs from iiif thumbnail feature.
=> Essi-135 iiif spec fixes

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/dashboard.scss, app/views/hyrax/base/_show_actions.html.erb
The changes include:
1) Commented structure_manager link out to fix the error when load the page.
2) broadened the grab area
3) Added the background color and border to make it look pretty
=> ESSI-153 tweak css to broaden grab area

Gemfile, Gemfile.lock, Rakefile, app/assets/javascripts/bulk_labeler/bulk_label.es6, app/assets/javascripts/bulk_labeler/label_generator.es6, app/assets/javascripts/bulk_labeler/labeler_actions_manager.es6, app/assets/javascripts/essi_boot.es6, app/assets/javascripts/file_manager/bulk_actions.es6, app/assets/javascripts/file_manager/essi.es6, app/assets/javascripts/file_manager/iiif_fields.es6, app/assets/javascripts/file_manager/radio_tracker.es6, app/assets/javascripts/file_manager/select_tracker.es6, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/essi_file_manager.scss, app/views/hyrax/base/_bulk_labeling_form.html.erb, app/views/hyrax/base/_file_manager_resource_form.html.erb, config/routes.rb, spec/javascripts/label_generator_spec.js, spec/javascripts/structure_parser_spec.coffee, spec/javascripts/support/jasmine.yml
Adds JavaScript for calculating and applying bulk labeling based on patterns supplied by user.  This consists of a number of JS components that calculates new labels given the pattern and applies them to the label fields for pages in the sortable grid.  
Bulk labeling relies on JQuery Selectable since files must be clicked and chosen to activate the user interactions in the toolbar, so this PR also includes all the JS File Manager components to enable Selectable.
This also adds the Jasmine JavaScript testing framework in order to reuse some legacy JS unit/feature tests.
=> ESSI-136 Add bulk labeling to File Manager

app/assets/javascripts/file_manager/bulk_actions.es6, app/views/hyrax/base/_file_manager_bulk_form.html.erb, app/views/hyrax/base/_file_manager_resource_form.html.erb, spec/javascripts/bulk_actions_spec.coffee, spec/javascripts/fixtures/bulk_action.html
The bulk action will show when one or several images/resources are picked.
=> essi-137 bulk page view action

app/assets/stylesheets/hyrax/_viewer.scss, app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
According to the hyrax style, I put 10px padding in. Now the uv size plus padding is 800px.
=> ESSI-286 Make universal Viewer size taller

config/environments/production.rb, config/essi_config.example.yml
Fixes various services that depend on knowing the site url.
=> Add Action Mailer default host to ESSI config.

app/actors/essi/actors/create_with_remote_files_actor.rb, config/browse_everything_providers.yml, config/essi_config.example.yml, config/initializers/aws-s3.rb
Setup for using a self hosted s3 compatible file store with BrowseEverything.
=> Essi 284 minio s3

app/assets/stylesheets/brand.css
Enforces the override introduced in fb6e88cfa
=> Enforce font-size override in branding CSS

.solr_wrapper, app/indexers/essi/file_set_indexer.rb, app/models/solr_document.rb, app/presenters/hyrax/displays_image.rb, config/initializers/add_viewing_hint_to_file_sets.rb
The change will fix both ESSI-413 (UV download current view image) and ESSI-414 (UV download original image) issue.
=> Essi 413 uv download

app/assets/javascripts/structure_manager.es6, app/assets/stylesheets/components/structure_editor.scss, app/views/hyrax/paged_resources/structure.html.erb, config/locales/structure_editor.en.yml
Also i18n's save button.
Current master appears to have already fixed inability to hide thumbnails and add section.
=> Prevents thumbnails from appear outside of structure node div.

solr/config/schema.xml
This is at least one reason complete processing and attachment of OCR can fail.
=> [ESSI-648] Disabling the creation of SOLR auto-suggest field

config/database.yml
Set default to 12 (Sidekiq concurrency + 2)
=> Allow db connection pool to be configurable

Gemfile, Gemfile.lock
Also remove puma pin to eventually allow 4.x
=> Security update for puma and nokogiri

app/assets/javascripts/hyrax/collections/collections.js, app/views/hyrax/collections/_collection_row.html.erb, app/views/hyrax/collections/_show_parent_collections.html.erb, app/views/hyrax/collections/_subcollection_list.html.erb, app/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb, app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb, app/views/hyrax/dashboard/collections/_subcollection_list.html.erb, app/views/hyrax/dashboard/collections/_subcollection_row.html.erb, config/locales/hyrax.en.yml
Revises display of parent and subcollections from an unordered list to a table layout similar to that used for child works.
=> [ESSI-760] Improve sub- and parent collection display

.gitignore, Dockerfile, Gemfile, config/essi_config.docker.yml, config/initializers/bulkrax.rb, db/schema.rb
JIRA: https://bugs.dlib.indiana.edu/browse/ESSI-874
**NOTES:** 
- This work does not completely resolve ESSI-874. See subtask: https://bugs.dlib.indiana.edu/browse/ESSI-903
- More configurations will be needed. See ticket: https://bugs.dlib.indiana.edu/browse/ESSI-902
- CSV file's required fields: [title, source_identification]
=> Essi-874 bulkrax import bug

app/views/catalog/_index_list_default.html.erb
ESSI-879 Truncate collection description to max 160 chars in search catalog results. 2 commits according to the convention. one is copied over the file from hyrax repo, another is making the change.
=> Essi 879 truncate description

app/controllers/purl_controller.rb, config/routes.rb, spec/controllers/purl_controller_spec.rb, spec/routing/purl_routing_spec.rb
Ports over updates from pumpkin PRs 210 and 214
=> [ESSI-918] Update purl controller for identifier matching

config/essi_config.docker.yml, docker-compose.yml
Create service in docker-compose for persistent redis for sidekiq jobs
=> ESSI-950 Setup redis for jobs

Gemfile.lock, config/cable.yml, config/environments/production.rb, config/essi_config.docker.yml, config/essi_config.example.yml, config/initializers/cable.rb, config/initializers/redis_config.rb, config/initializers/sidekiq.rb, config/redis.yml, docker-compose.yml
Cleans up redis configuration to be more flexible and adds a possible workaround to ActionCable/redis disconnection problems.
=> Essi-1027 ssl redis

app/views/_masthead.html.erb, app/views/hyrax/base/show.html.erb, app/views/hyrax/collections/show.html.erb, app/views/hyrax/file_sets/show.html.erb, app/views/shared/_collection_banner_for_collection.html.erb, app/views/shared/_collection_banner_link.html.erb, app/views/shared/_collection_title_link.html.erb
There are two places to move the collection banner image up. One is for the work which belong to a collection(has a banner image). Another is for the collection( with the banner image) itself.
=> Essi 993 collection banner image

app/assets/stylesheets/brand_tweaks.css, app/assets/stylesheets/digital_collections.scss, app/assets/stylesheets/digital_collections/_layout.scss, app/assets/stylesheets/iu-framework.min.buttons.css, app/views/hyrax/homepage/_home_content.html.erb, app/views/hyrax/homepage/_home_content_campuses.html.erb, app/views/hyrax/homepage/_home_content_welcome.html.erb, app/views/hyrax/homepage/index.html.erb
Modify homepage to single-column layout and other style tweaks
=> [ESSI-1008] Homepage tweaks

.circleci/config.yml
The image built in Circle was still using the testing debian repo for tesseract packages. Those packages seem to be broken currently. This updates the build to match our Dockerfile and docker-compose environment.
=> Update CircleCI test image to match Dockerfile

app/views/shared/_footer.html.erb
Move Digital Collections and Samvera Hyrax version/release information from mahogany footer to "About" page
=> ESSI-1082 Move some footer info to About page

app/jobs/perform_later_actor_job.rb, app/jobs/save_structure_job.rb
Don't use the "default" queue in Sidekiq
=> Use configured queues instead of "default"

app/controllers/hyrax/collections_controller.rb
Same as #245 but with the original file copied in its own commit.
=> Essi-1167 disable bookmark

app/assets/stylesheets/digital_collections/_fonts.scss, app/views/catalog/_search_form.html.erb, config/locales/hyrax.en.yml
There are two commits. According to our convention,
The first commit is to copy the file "_search_form.html.erb" over from the hyrax repo.
The second commit is the customization on file "_search_form.html.erb" and other files change.
=> Essi 1287 search bar

app/assets/stylesheets/digital_collections/_layout.scss
Adjust the space between two buttons.
=> ESSI-1302 Make two buttons have bigger space between them

app/models/concerns/mets_structure.rb, app/models/mets_document.rb, spec/fixtures/xml/mets.xml, spec/models/concerns/mets_structure_spec.rb
Change labeling logic/preferences from:
FILEID --> ID --> TYPE ORDER
to
LABEL --> ID --> TYPE ORDER
=> [ESSI-1223] Bulkrax METS labels

app/models/concerns/mets_structure.rb
=> [ESSI-1223] Remove debugger line that got committed

app/services/cover_page_generator.rb
Handles rights_statement whether singular or multi-valued; currently single-valued and broken.
=> Fix cover page bug re: singular rights_statement

lib/extensions/allinson_flex/prepend_profile.rb, lib/extensions/allinson_flex_extensions.rb, lib/extensions/bulkrax/entry/dynamic_schema_field.rb
First commit fixes an essi bug.
Second, third commits address https://github.com/samvera-labs/allinson_flex/issues/76
=> [ESSI-1370] Bulkrax export bugs

lib/extensions/bulkrax/import_work_collection_job/add_user_to_permission_template.rb, lib/extensions/extensions.rb, spec/features/csv_importer_spec.rb
Attempts to resolve current errors on:
https://dcadmin-devel.dlib.indiana.edu/importers/17?locale=en
=> [ESSI-1424] bulkrax csv import errors

app/services/cover_page_generator.rb, spec/services/cover_page_generator.rb, spec/services/essi/generate_pdf_service_spec.rb
See follow-up PR #369 to resolve FIXME lines.
=> [ESSI-1539] Fix PDF cover page for nil rights_statement

app/models/user.rb, spec/models/user_spec.rb
=> essi-1555 Tweaks to pass specs

app/controllers/catalog_controller.rb, app/indexers/concerns/essi/indexes_collection_descendants.rb, app/indexers/essi/collection_indexer.rb, app/indexers/essi/collection_metadata_indexer.rb, app/indexers/essi/file_set_indexer.rb, app/models/collection.rb, app/models/concerns/essi/collection_behavior.rb, app/models/solr_document.rb, app/views/hyrax/homepage/_home_content_campuses.html.erb, config/initializers/samvera-nesting_indexer_initializer.rb, lib/extensions/extensions.rb, lib/extensions/hyrax/collection_presenter/total_counts.rb, lib/tasks/update_collection_descendants_count.rake
The final commit isn't strictly necessary, as it's just copying that file in from hyrax without modification, but I felt inclined to make that hidden, inherited setting about the maximum nesting depth (5) explicit within the project.
In draft status pending adding specs.
=> [ESSI-1566] Catalog sorting collections by "size"

app/views/hyrax/homepage/_home_content.html.erb
Was causing a syntax error on the homepage
=> essi-1595 Fix missing comma

app/models/concerns/essi/collection_behavior.rb
Indexing was breaking with more than 96 children of a Collection.  This restricts walking the subtree to ignore non-collections, and to cap solr searches at 96 id values.  This should prevent solr errors, although if more than 96 collections are nested at any specific depth level of the nesting tree for a primary collection ancestor, collections after the 96th will not be counted.
=> [ESSI-1566] Scaling fix for collection count methods

spec/services/hyrax/collections/collection_member_service_spec.rb
@randalldfloyd these specs should pass as-is, or fail if you run with reverting #425
=> [ESSI-1578] Change collection search spec to user presenter

Dockerfile
Fixes SaveStructureJob failing on large works.
=> ESSI-1612 Increase VM stack size to match machine stack size

Gemfile.lock
Our fork of allinson_flex now eager loads some relationships to avoid a bunch of n+1 queries during profile saving.
=> Essi-1613 `bundle update allinson_flex` to get profile saving optimization

yarn.lock
=> yarn updates

yarn.lock
This reverts commit bcd5c4337959e7995694125d1919f636820a9b62.
Caused docker image build to fail, unable to find webpack.
=> Revert "yarn updates"

config/environments/development.rb, config/environments/production.rb, config/essi_config.docker.yml, config/essi_config.example.yml
Requested to to reduce the size and noise of the public server's logs.
=> Essi-1682 Add logging level configuration

app/services/essi/adapters/nesting_index_adapter.rb
_in draft status pending merging of #478_
Populates campus_sim with the directly-provided value (if present) merged with values (if present) provided by collection ancestry.
Note that this can lead a work or collection to have multiple distinct values, by placing it in collections across campuses.
=> [ESSI-1624] inherit campus value

app/controllers/application_controller.rb, app/controllers/concerns/essi/public_access_behavior.rb, app/views/hyrax/dashboard/_sidebar.html.erb, app/views/hyrax/dashboard/sidebar/_activity.html.erb, config/essi_config.docker.yml, config/essi_config.example.yml, config/routes.rb
* New method for defining filtered controller actions
* Removes corresponding section from routes.rb
* Prevent rendering of some dashboard sidebar entries
=> Essi-1689 Reimplement access_only filters for improved control

app/controllers/catalog_controller.rb
Simple config change to remove slideshow from collection index and collection home pages.
=> [ESSI-1672] Remove Slideshow

lib/extensions/hyrax/collection_presenter/total_counts.rb, lib/extensions/hyrax/forms/collection_form/all_files_with_access.rb
Some older monkeypatches had stale "unmodified" comments
=> revise comments for monkeypatches

app/models/jsonld_record.rb, lib/iu_metadata/client.rb, spec/fixtures/vcr_cassettes/bibdata.yml, spec/fixtures/vcr_cassettes/mods_VAD5427.yml, spec/fixtures/vcr_cassettes/mods_deadbeef.yml
Revise "MODS" lookup to "mods", and remove error raising for missing MODS
=> Downcase recordSchema argument from MODS to mods

Dockerfile
Enabling jemalloc to reduce memory fragmentation as suggested by @orangewolf
=> Use jemalloc and update to ruby 2.7.7

.github/workflows/dockerimage.yml, .github/workflows/dockerimage_stable.yml, .github/workflows/dockerimage_test.yml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
=> Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

config/initializers/sidekiq.rb
This will enable us to run additional sidekiq processes dedicated to specific queues
=> essi-1807 Allow Sidekiq queue to be set from ENV

Dockerfile
Prevents some JP2000 files being identified as MS Word files
=> ESSI-1819 Disable FFIdent

.circleci/config.yml
These are included in the ci base image
=> Remove NodeJS & Yarn from CircleCI deps

app/controllers/purl_controller.rb, config/essi_config.docker.yml, config/essi_config.example.yml
This PR relaxes the validation rules for incoming IDs and makes the regex pattern configurable.
=> ESSI-1908 Relaxing PURL validation rules

app/assets/stylesheets/brand.css, app/assets/stylesheets/brand_tweaks.css, app/views/shared/_footer.html.erb
Those changes fix ESSI-1893, ESSI-1896 and ESSI-1900. All are for footer accessibility, so I put them in one commit.
=> ESSI-1893 footer changes for accessibility

app/views/hyrax/users/_activity_log.html.erb
Fixes essi-1902 by rendering a static table row when the events list is empty.
=> Essi-1902 Essi-1860 Remediation of empty events table

.circleci/config.yml, lib/extensions/allinson_flex_extensions.rb
- Restores functionality of the tests tab in circleci (results were being saved to wrong location)
- Turns on parallelism to speed up specs
- Makes sure an admin exists before initializing models
- Update ruby orb to get rerun failed specs function
- Allow minor updates for browser tools orb
=> Spec improvements

app/assets/stylesheets/digital_collections/_layout.scss
Fixes color contrast issue for striped tables. Should now pass AA and AAA standards, plus part of IU color scheme.
=> Changes striped table link color to IU Dark Midnight 

app/assets/stylesheets/digital_collections/_layout.scss
All links will be underline by default and no line if hover or focus. This will affect a lot of links.
=> ESSI-1897 accessibility improvement for default link

Dockerfile
cherry-picking backport into 1.4.13
=> backport Dockerfile change to resolve bundler/byebug conflict

app/services/essi/generate_pdf_service.rb
PDF generation currently hardcodes an image width of 1024.  Our IIIF image server returns a 403 if you try to render an image at great than 100% width, which breaks the PDF generation that page if the image is too narrow, and broken generation of any page breaks PDF generation for the entire work.
This changes the IIIF request to send a image width value of:
* if the image is at least 1024 wide: 1024, as before
* if the image is narrower: the actual image width
Further details:
* added more error catching and logging
* if image width is _missing_ from indexed characterization results, it attempts to (re-)call characterization -- first directly, just to get the width value and use it, and subsequently spawning the job
=> [ESSI-1939] fix PDF generation for image widths below 1024

app/views/_ga.html.erb, config/essi_config.docker.yml, config/essi_config.example.yml, config/initializers/hyrax.rb
Override hyrax's _ga.html.erb with what is needed by GA4, and set the id from essi config.
=> ESSI-1966 Add analytics JS and config

app/controllers/catalog_controller.rb, app/helpers/facet_helper.rb, app/helpers/hyrax_helper.rb
Changes display of code values like "IUI" to labels like "IU Indianapolis"
=> [ESSI-1996] campus facet: display label rather than code value

app/jobs/characterize_job.rb
Downloads an externally stored file to the hyrax working dir during characterization and derivative generation.
=> ESSI-2043 Ensure external file is available during charecterization

Gemfile, Gemfile.lock, app/controllers/rack_attacks_controller.rb, app/views/hyrax/dashboard/sidebar/_configuration.html.erb, app/views/rack_attacks/_form.html.erb, app/views/rack_attacks/edit.html.erb, app/views/robots/edit.html.erb, config/essi_config.docker.yml, config/essi_config.example.yml, config/initializers/rack_attack.rb, config/routes.rb, lib/essi_dev_ops/rack_attack_config.rb
Adds rack attack gem and the ability to dynamically control the ip addresses and user agents it acts upon via a yaml block in a text dashboard form.
=> ESSI-2079 Add rack attack

app/views/rack_attacks/_form.html.erb, app/views/rack_attacks/edit.html.erb, config/initializers/rack_attack.rb, lib/essi_dev_ops/rack_attack_config.rb
Add safe paths, enable retry-after, display more config.
=> ESSI-2079 Iterating on rack attack

app/authorities/qa/authorities/iucat_libraries.rb, config/authorities/supplemental_holding_locations.yml
Also sort combined holding locations (from API, supplemental YAML) by labels
=> [ESSI-2087] add B-MPP to supplemental holding locations

app/views/hyrax/base/_a11y_remediation.html.erb, app/views/hyrax/base/show.html.erb, app/views/hyrax/file_sets/_show_actions.html.erb, app/views/hyrax/file_sets/show.html.erb, app/views/shared/_footer.html.erb, config/locales/hyrax.en.yml
Also removes Social Media links from Item and File Set pages.
=> [Essi 2093] Add accessibility remediation request and support links 

lib/extensions/bulkrax/create_relationships_job/depositor_parent_permissions.rb, lib/extensions/extensions.rb
Raised in bulkrax as https://github.com/samvera/bulkrax/issues/1034
=> [ESSI-2099] fix bulkrax import with depositor permissions on parent

Dockerfile
See https://github.com/harvard-lts/fits/pull/408
Resolves ESSI-2135
=> Modify FITS exiftool image metadata mapping for pyramidal tiffs
